### ISSUE TITLE
"Extra Stats" are unreadable when dark styles are applied

### ISSUE THREAD

**Issue by ChrisMBarr** [FMaz008/VineHelper#104]
**VH Version**: `2.4.18`
**Browser**: Firefox `124.0.2`
**Issue:** Enabling the `dark-theme.css` styles, the "extra stats" are unreadable

(Edited image out)

**Comment by FMaz008** [comment]
I'll look into it next week. :)
 I removed your images and video.

**Comment by FMaz008** [comment]
Fixed :)

**Comment by ChrisMBarr** [comment]
so now it seems to have the opposite problem. When I turn the dark theme OFF, the extra stats appear dark. It looks like it's just hard-coded to be always dark no matter what
