### ISSUE TITLE
Feature Request: Favorites

### ISSUE THREAD

**Issue by vinnn-90** [FMaz008/VineHelper#108]
Hi there,

May i suggest a feature here?

I was thinking of a new tab like the one used for notification monitoring but instead showing a list of favorited items.
That would need the addition of a button at each item (a star for example) to add items to the favorites list.

The most important part though, would be integrating the same magnifying glass functionality that already exists in the notification monitoring tab. That would allow users to quickly jump to the page where the item is listed. 

I would love this feature in cases when I dont want to order an item immediately or I have reached my daily limit.
Saving me from looking through countless pages for the correct item. Even if I have hidden most other items, I still have to go through the pages to find the one I am looking for. Since items in general often do move to other pages, taking note of the page number doesnt help in most cases.

Anyway, thanks for VineHelper, its already helping alot <3

**Comment by FMaz008** [comment]
Done, the feature is called Pinned items.
