### ISSUE TITLE
Feature Request: Include the details toolbar on the product details modal

### ISSUE THREAD

**Issue by ChrisMBarr** [FMaz008/VineHelper#109]
Right now to announce an item with an unknown ETV is a step process:
1. click "see details" top open the modal
2. when it opens, close it immediately
3. now you can click the button

![3-step-announce](https://github.com/FMaz008/VineHelper/assets/463685/e29ae90a-d24f-4d1d-aa72-c3245d71c31f)

I understand that the ETV must be known, but I think a good solution to simplify this process and make it easier would be to just include the details toolbar somewhere in the open modal. This would help for announcing products, but also the other features it offers from right there too.

Here's a quick and dirty mockup of what that could possibly look like.
![image](https://github.com/FMaz008/VineHelper/assets/463685/862be18d-c04e-4eaa-a3f5-26a8779dfebc)

Or perhaps down at the bottom with the other buttons makes more sense. The placement may not mater too much, but to have this inside the modal might be very useful.
![image](https://github.com/FMaz008/VineHelper/assets/463685/29b1b7ce-cfb5-4887-a412-b8835ac5cb16)

**Comment by FMaz008** [comment]
Thank you for your detailled suggestion.

The ETV is already displayed in the modal window for the countries where it matters.

The ETV is not always a reflection of an item's value and will differ from an account to the other.

Last, Vine Helper tried not to interfere with the modal window.

**Comment by ChrisMBarr** [comment]
So are you saying it's not feasible to have an "announce" button in the modal?

**Comment by FMaz008** [comment]
No, that is not what I said. And in fact there is a userscript doing exactly just that which already exist. :)
