### ISSUE TITLE
When selecting a category on the left side with the (always show 1-# on the top), the numbers overlap eachother. See screenshot.

### ISSUE THREAD

**Issue by sorphin** [FMaz008/VineHelper#110]
<img width="730" alt="Screenshot 2024-05-09 at 4 17 32 PM" src="https://github.com/FMaz008/VineHelper/assets/496131/69dd1a4a-2d23-45ad-b1e0-eafc56073591">

Running 2.5.2 via GH from a couple days ago.

**Comment by FMaz008** [comment]
Oh wow. I could not reproduce precisely your bug but I found that the expanded pagination was completely broken when using categories. I've fixed that in the code base... But I'm not sure that explains why you have a "6" at the end of what you are showing me in the screenshot.

**Comment by FMaz008** [comment]
I think v 2.7.0 should fix this. Can you confirm ?
