### ISSUE TITLE
Infinite spinning wheel

### ISSUE THREAD

**Issue by iTsYaBoiiiiii** [FMaz008/VineHelper#116]
There is currently an item in UK AI that has an infinitely spinning wheel.

![image](https://github.com/FMaz008/VineHelper/assets/32450703/54a3c7d8-281d-4f83-aa28-eb1cf7b3ccc8)

The item in question: https://www.amazon.co.uk/dp/B0D4Q3M7D7

**Comment by iTsYaBoiiiiii** [comment]
Looking at the console as I click on the item I do not get any error.

**Comment by iTsYaBoiiiiii** [comment]
The json for the request:

{
    "result": {
        "recommendationId": "A1F83G8C2ARO7P#B0D4Q3M7D7#vine.enrollment.b393a4ad-ad03-4ea5-a7e3-42d2936072b4",
        "enrollmentAsinType": null,
        "item": null,
        "variations": [
            {
                "asin": "B0D4PJT25K",
                "dimensions": {
                    "Colour Name": "Red",
                    "Size Name": "XXL"
                }
            },
            {
                "asin": "B0D4PMM1GJ",
                "dimensions": {
                    "Colour Name": "Red",
                    "Size Name": "L"
                }
            },
            {
                "asin": "B0D4PV24GN",
                "dimensions": {
                    "Colour Name": "White",
                    "Size Name": "M"
                }
            },
            {
                "asin": "B0D4PX2NWQ",
                "dimensions": {
                    "Colour Name": "White",
                    "Size Name": "XXL"
                }
            },
            {
                "asin": "B0D4PX5F8V",
                "dimensions": {
                    "Colour Name": "Purple",
                    "Size": "L"
                }
            },
            {
                "asin": "B0D4PX6PTT",
                "dimensions": {
                    "Colour Name": "White",
                    "Size Name": "S"
                }
            },
            {
                "asin": "B0D4Q12GWX",
                "dimensions": {
                    "Colour Name": "White",
                    "Size Name": "XL"
                }
            },
            {
                "asin": "B0D4Q5NBLN",
                "dimensions": {
                    "Colour Name": "White",
                    "Size Name": "L"
                }
            },
            {
                "asin": "B0D4Q5PCB9",
                "dimensions": {
                    "Colour Name": "Purple",
                    "Size Name": "XL"
                }
            },
            {
                "asin": "B0D4Q6S5RT",
                "dimensions": {
                    "Colour Name": "Red",
                    "Size": "M"
                }
            },
            {
                "asin": "B0D4Q86KFH",
                "dimensions": {
                    "Colour Name": "Purple",
                    "Size Name": "S"
                }
            },
            {
                "asin": "B0D4Q9N83Q",
                "dimensions": {
                    "Colour Name": "Purple",
                    "Size Name": "XXL"
                }
            },
            {
                "asin": "B0D4Q9P9H2",
                "dimensions": {
                    "Colour Name": "Red",
                    "Size Name": "S"
                }
            },
            {
                "asin": "B0D4QCQ6NC",
                "dimensions": {
                    "Colour Name": "Red",
                    "Size Name": "XL"
                }
            },
            {
                "asin": "B0D4QCQW1D",
                "dimensions": {
                    "Colour Name": "Purple",
                    "Size": "M"
                }
            }
        ]
    },
    "error": null
}

**Comment by iTsYaBoiiiiii** [comment]
After the initial fetch request after clicking on the item (initiated by inj.js:7) I dont seem to get a second fetch for the image

**Comment by FMaz008** [comment]
That's odd. Every infinite spinner I have ever encountered always produce a track & report error. Do you mind checking again? Note that the content of the modal window is cached so you might need to reload the page, open the console, (clear it) and then try to open the item to get the error.

Good work on getting the XHR request. Idon't see anything weird about it tho, not sure why this item is a spinner. Usually it occurs when the "dimensions" are empty, or the children elements of dimensions have special characters in them

**Comment by iTsYaBoiiiiii** [comment]
I reported a similar bug some time ago and that one did produce an error in the console - it ended up being a character that wasn't being handled.
This time however there is nothing in the console and I have refreshed and checked multiple times. It's always the same.

Having said that, this is what a normal request usually looks like to me:
![image](https://github.com/FMaz008/VineHelper/assets/32450703/dea0c4ed-40e5-4ec9-a624-c3ce5df6d659)
Upon clicking an item I first have a fetch request coming from ini.js:7 and then a secondary fetch for the image (also ini.js:7).
Then a third from ini.js:99

On this item however only the first fetch is sent and no subsequent fetches go through:
![image](https://github.com/FMaz008/VineHelper/assets/32450703/3da0b5dc-d70c-405b-b15a-8f1426867434)

**Comment by iTsYaBoiiiiii** [comment]
The callstack between the working and non-working fetch seems to be the same...

**Comment by iTsYaBoiiiiii** [comment]
For some added context, I do get these warnings in the console periodically, however I would assume that they are unrelated:
![image](https://github.com/FMaz008/VineHelper/assets/32450703/15873239-8f5f-4d19-847c-99b3a8c8739d)

**Comment by FMaz008** [comment]
Yes those warnings are not relevant. But I've never seen amazon not giving random errors. It's odd to see a console without any errors. Are you sure you're not filtering by warnings or something?

**Comment by iTsYaBoiiiiii** [comment]
I have the console set to all levels

**Comment by FMaz008** [comment]
I have no idea then. If you disable VH you get the same spinner?

**Comment by iTsYaBoiiiiii** [comment]
I _sometimes_ get this error, however I again thought this is unrelated:
![image](https://github.com/FMaz008/VineHelper/assets/32450703/f851d524-6c1d-4f32-8419-4e2ffe8f40c2)

**Comment by iTsYaBoiiiiii** [comment]
> I have no idea then. If you disable VH you get the same spinner?

Same issue with VH disabled

**Comment by FMaz008** [comment]
Ok, well I don't have much to go on, and it's not a Vine Helper issue per say.

So I'll close the issue for now but we'll reopen it if we can get a proper clue as to what's going on.
