### ISSUE TITLE
Feature Request: Sync Pinned Items

### ISSUE THREAD

**Issue by ZUUL42** [FMaz008/VineHelper#117]
Currently hidden items are synced between devices with the same UUID.
With the addition of Pinned Items, it would be exceptionally useful to add Pinned Items to the synced data.

As things are, I use the Pinned Items, but still find myself creating a "Pinned Searches" folder in my bookmarks, so Chrome will sync them for me.

Syncing settings would also be helpful, but those are a small set that mostly remains static.

**Comment by FMaz008** [comment]
I hate how right you are...

I'll work on this when I have some time :)
