### ISSUE TITLE
Do not display "shared etv" in pop up notifications

### ISSUE THREAD

**Issue by RealFakeGitter** [FMaz008/VineHelper#118]
It would be nice if the popup notifications only showed new items not popup every time you share an etv, there are many notifications and it gets overwhelming. Or at least a way to shut it off and only display new items and nothing else. 

![image](https://github.com/user-attachments/assets/49ad24e5-9bf5-43d3-b309-3b0a990fa507)

**Comment by FMaz008** [comment]
That popup should be displayed under the modal window and vanish after 3 sec. It's merely there as a transparency way of showing something was shared with the server.

I'm not sure I understand how it is inconvenient, are you opening and closing multiple items within 3 seconds?

**Comment by FMaz008** [comment]
I added a "Reduce Notifications" option in the general tab which get rid of the ETV notifications and the Settings Saved notifications.

It's available in the code base, or with the next release in a few days... :)
