### ISSUE TITLE
Shared UUID not working

### ISSUE THREAD

**Issue by skotl** [FMaz008/VineHelper#119]
Been a VH user for several months now - thanks again for a great product!

I've been using the shared UUID across a desktop and two laptops since the feature was released and it's been working great, until I wiped one of the laptop and reinstalled (Windows 11: Reset your PC).
I enter the UUID being shared on the other machines and it has saved (and displays correctly when I hover over it) but this reinstalled laptop isn't syncing with the other pair.

There's obviously little to get wrong here so wondered if you had any pointers? Edge 127.0.2651.74 on Windows 11 Version 23H2 (Build 22631.3958)

**Comment by FMaz008** [comment]
On your new installation, do you have the Remote Storage enabled?

**Comment by skotl** [comment]
Apologies for taking so long to respond.
Of course, you're correct: my initial thought was that perhaps this could be mitigated by having Remote Storage and UUID on the same page (or repeat one of the settings near the other) but I just went to check and have been confronted with the new config screen with multiple pages and now I can't even find the UUID setting!

Slightly off topic, perhaps, but it probably does fall under UX and I'm afraid to say that the new settings dialog is a pretty poor experience.

  _(note: nothing worse than a trenches-bound sniper - I'll try to come up with constructive suggestions)_

**Comment by FMaz008** [comment]
General tab,
Tabs section,
Under Hidden Tab: Store Hidden/Pinned Items Remotely.

**Comment by FMaz008** [comment]
Also, fair point about the placement of the Remote storage option. It used to make sense as it was strictly pertaining to the Hidden items, but now that it also apply to the Pinned tab, it makes more sense to move the settings under the UUID.

This change will be effective as of V2.8.11, but for now you can find it where I indicated above.

**Comment by skotl** [comment]
No issue
