### ISSUE TITLE
Improvement: hover over text to get the full text

### ISSUE THREAD

**Issue by Wladefant** [FMaz008/VineHelper#122]
https://github.com/therealglazou/vineplusplus has an implementation of that

**Comment by FMaz008** [comment]
Have you tried the style sheet "more-description-text"?

But a hover text bubble with the complete text is a really good idea, especially for those using small items display.

I like this.

**Comment by Wladefant** [comment]
Yes tried it, still not the full title

**Comment by FMaz008** [comment]
Done with commit 1e8ff05b7a41294f21721bdc1d38a049222610b9, will be available with the next release. This needs to activate an option under the general tab in the settings.
