### ISSUE TITLE
Is it posssible to prevent scrolling on "hide all"?

### ISSUE THREAD

**Issue by chris-thorn** [FMaz008/VineHelper#128]
**Describe the bug**
VH scrolls to the top of the RFY/AFA/AI buttons when `hide all` is selected, but as I progress to a new page, my browser begins at the top of the page, and I have to then scroll back down to the products. I find it a bit jarring with the browser frequently smooth-scrolling down as you quickly progress between pages.

**To Reproduce**

1. Using amazon.co.uk
2. Go to AI
3. Click on `Hide` (or keyboard `h`)
4. Browser scrolls to top of RFY/AFA/AI buttons
5. Click on another page, select `n` on keyboard, or use `Hide + next` in step 2
6. Browser now starts at top of page (remove-header.css is in use in VH style settings)

**Expected behavior**
Allow user to choose whether `hide all` scrolls to top of buttons after hiding items.

**(optional) Screenshots**
Relevant lines (255 onwards) from https://github.com/FMaz008/VineHelper/blob/aac12e07ee89f8c392dd011774e15b3a0a57a8ca/scripts/grid.js#L255

	// Scoll to the RFY/AFA/AI header
	var scrollTarget = document.getElementById("vvp-items-button-container");
	scrollTarget.scrollIntoView({ behavior: "smooth" });

**Browser**
 Chrome

VH is a great project, but I just can't figure out why it automatically scrolls when everything has been hidden!

Thanks!

**Comment by FMaz008** [comment]
You win the most detaillee bug report. Haha, good job!

I think it's probably just missing a return false on the click so it go to the anchor link `#`, which goes at the top of the page.

I'll look into it.

**Comment by FMaz008** [comment]
Hold on, just so I understand, is your problem that hide all scroll back to RFY/AFA/AI buttons, of that when you go Next Page that the new page is scrolled at the very top?

**Comment by chris-thorn** [comment]
Thanks for the quick reply!

Sorry about the wording - I struggled to describe it very well.

I actually think that what I am perceiving as a "problem", is simply the fact that "hiding all" scrolls the browser to the top of the RFY/AFA/AI buttons, but when a new page is loaded the browser understandably starts at the top of the page. I'm not a huge fan of the browser controlling where I scroll on a page, and the smooth scrolling animation means that it takes a moment for the page to scroll to position when I click "hide all".

In my humble opinion, it might be good to either:

- Allow the user to select an option whereby every time they land on an AI page, the browser scrolls to the top of the RFY/AFA/AI buttons, which would match the behaviour of the `scrollIntoView` function that runs on "hide all".
- Allow the user to disable the `scrollIntoView` functionality of "hide all", so VH doesn't take over any of the scrolling behaviour.

I hope that makes a bit more sense!

**Comment by FMaz008** [comment]
Released along with v2.8.4

https://github.com/FMaz008/VineHelper/commit/5b1bbd254869b3c058430d5b229f6fbdbc126330
