### ISSUE TITLE
Notification monitor tab: 0etv sound effect play but item remain hidden when using the filter.

### ISSUE THREAD

**Issue by 1920x1200** [FMaz008/VineHelper#129]
If you leave the "Notifications Monitoring" tab open, it checks for updates every 30 seconds. Sometimes the sound plays for a notification but nothing appears. To fix it, you have to refresh the page and click "fetch last 100" and then the item appears. Sometimes it works fine for hours while other times it can occur after just 15 mins. 

**To Reproduce**
0. Using amazon.com
1. Go to Vine Helper icon in browser toolbar
2. Click on Notifications Monitoring
3. Leave tab open for 15-60 mins
4. Wait till you hear the sound but nothing new appears. 

**Expected behavior**
The item should always appear on the page whenever a sound plays

**(optional) Error in the developer console**
I don't see any related to Vine Helper

**Browser**
Firefox 130, macOS 14.5

**Comment by FMaz008** [comment]
Do you have the option Hide notifications with auto-hide keywords activated?

Do you have filters active for the notifications monitor?

**Comment by 1920x1200** [comment]
> Do you have the option:
> 
>     * Hide notifications with auto-hide keywords
> 
>     * or
> 
>     * hide notifications with duplicate images
>       activated?
> 
> 
> Do you have filters active for the notifications monitor?

Yes, I have both of those options checked and I do have keywords in the Highlight items keywords and Auto-hide items keywords sections.

**Comment by FMaz008** [comment]
So the bug is probably that it's playing a sound when it should not because the item gets hidden (hidden lost or duplicate image).

**Comment by 1920x1200** [comment]
> So the bug is probably that it's playing a sound when it should not because the item gets hidden (hidden lost or duplicate image).

That sounds reasonable to me. Is there anything I can do to help debug this so it can be corrected?

**Comment by FMaz008** [comment]
Not really. The upcoming release in October will have real time notification so it's all new code anyway ..

**Comment by LitBomb** [comment]
I have the same problem, but I have neither "Hide notifications with auto-hide keywords" nor "hide notifications with duplicate images activated".

I only have "Check for New Items" and "Push NOtification when KW match" checked, and "Match Highlight KW sound set to "upgrade".  The other two sounds are set to "none".  

Also, a separate bug, if there is a Windows notification pop up, and I click on it, it goes to the vine page to search for "undefine".

**Comment by LitBomb** [comment]
I think I see what is going on.  On the Notifications monitoring page, I set "filter by" to "KW  match only".  The display does filter to show only KW matched items, but it still plays the sound if there is *any* new item after a refresh, KW matched or not.

**Comment by FMaz008** [comment]
That is correct, the filter is just a visual filter, it does not affect the sound logic at this point in time.

**Comment by FMaz008** [comment]
Not that it was still a problem with 2.9.9, but it sound be even more fixed with v2.9.10 as I improved the logic of how sounds are being played between both notifications type and did some extensive testing.

Please re-open if you still have an issue.

**Comment by 1920x1200** [comment]
Unfortunately, this isn't fixed in 2.9.10
Still hearing the sound almost every 30 seconds when nothing is displayed. 

![Screenshot 2024-10-04 at 2 56 21 PM](https://github.com/user-attachments/assets/e3dd1665-0303-4ddf-b564-2f4728ec729f)

**Comment by FMaz008** [comment]
Do you have on screen notification enabled with sound?

**Comment by 1920x1200** [comment]
Here are my settings.
[settings.html.pdf](https://github.com/user-attachments/files/17263039/settings.html.pdf)

**Comment by FMaz008** [comment]
Whoch of the sound do you hear?

**Comment by 1920x1200** [comment]
Mostly the "Upgrade" sound which I have assigned to Zero ETV since those happen more often then when an item matches one of my keywords. I'm pretty sure I've heard both sounds though. Sometimes items display, sometimes they don't. In the past I would just refresh the page and click "fetch items" but now that the button was taken away, I have no idea what I'm missing.

**Comment by FMaz008** [comment]
Do you have multiple browsers running the extension?

**Comment by 1920x1200** [comment]
I'm only using Firefox. If I close the notification monitor tab, the sounds stop. 
I found the setting for "Instant Notifications" and just enabled it. A few mins later the sound went off (and the speaker icon lit up on the notification monitor tab) and when I switched to the tab, nothing was there.

**Comment by 1920x1200** [comment]
The issue appears to be with the "Zero ETV or KW Match only" option. I just discovered that if I change the drop down to just "Zero ETV", I see the missing items there. (the ones making the sound but not showing) I can then switch back to "Zero ETV or KW Match only" and the items remain.

**Comment by FMaz008** [comment]
Sounds like what I fixed earlier today (not released yet)

67e713f84c7be2910bfec4ff0c82c51ab5a0b994

Hopefully that's it.

**Comment by FMaz008** [comment]
Attempting to close this issue again with the mentioned fix. As usual don't hesitate to re-open if the issue persist on your end.
