### ISSUE TITLE
Display notification with details about yellow errors in modal window

### ISSUE THREAD

**Issue by FMaz008** [FMaz008/VineHelper#13]
When a yellow error happen in the modal window (See details), a notification could be shown stating the actual reason for the error.

The main challenge is for me to find such an item in Canada to code the solution.

**Comment by sorphin** [comment]
I'll keep a look out here in the US for a yellow error item... There have however been 2 RED errors recently and I thought it was just me, but a reddit thread said it wound up being everyone that tried it.

**Comment by FMaz008** [comment]
Seems those errors mainly happen to item that were just removed from enrollment. Have yet to capture one.
