### ISSUE TITLE
Complete stopped working after update to 2.9.3

### ISSUE THREAD

**Issue by MarcWinNJ** [FMaz008/VineHelper#132]
**Describe the bug**
Updated the chrome extension diversion 2.9.3. After the update the ETV value would just be a spinning wheel. Unable to send anything to the vine discord. I tried disabling and reenabling the extension and that did not work. I didn't removed the extension restarted chrome and reinstalled the extension and restarted chrome. I no longer have anything that Devine helper extension offered before. It's just a standard plain screen.

**To Reproduce**
0. Using amazon.com (US)

**Expected behavior**
The extension is installed, but doesn't show that it's installed

**(optional) Screenshots**
A screenshot also help knowing what display settings you are using to reproduce your problem.

**(optional) Error in the developer console**
(Right click anywhere, Inspect. Then check the console tab for any red error related to Vine Helper)

**(optional) Last page of Vine Helper debug log**
If you have an issue where the tabs are no longer showing the item count:
With the keybinding activated, press 'd' to show the debug log of vine helper, scroll down to the last page and copy its content. This should tell us where the execution of the script ended if an error was encountered.

**Browser**
 [e.g. chrome, firefox,  kiwi]
 
**Additional context**

**Comment by MarcWinNJ** [comment]
Update it came back but does not show the ETV, it just spins
![Screenshot 2024-09-30 at 9 29 34 AM](https://github.com/user-attachments/assets/90d71228-abad-4957-a20a-fefb05fae92d)

**Comment by MarcWinNJ** [comment]
Are you also the author of UltraViner?

**Comment by FMaz008** [comment]
Nop.

**Comment by FMaz008** [comment]
Should be fixed by now, if not, please re-open
