### ISSUE TITLE
Notifications of new items bring back old items too

### ISSUE THREAD

**Issue by urbanmoon** [FMaz008/VineHelper#135]
**Describe the bug**
When you clear the Notifications Monitor to have a clean and easy-to-process display of the next new items that arrive, the new items bring back old items, sometimes even looking like it hasn't even brought a new item. This new behaviour also makes the on-screen notification popups you get when on another tab unusable because the stack of popups has the newest at the very top, out of the screen range and the oldest are at the bottom, so you have to manually close each old popup before you get to the higher newer ones. This popup feature, as it was before, was very useful for managing what you see. I could be on another tab (RFY) or in a subcategory of AI and see what's new from elsewhere by those popups. It was also good if you accidentally reloaded the Notifications Monitor and cleared everything away, you could check a different tab to go through that stack of new item popups. That here-today-gone-tomorrow feature of showing us the last 100 items was excellent for those user blunders too. 

**To Reproduce**
Using amazon.ca

**Expected behavior**
1. I expect the Notifications Monitor to only bring in new items to display once the old ones have been cleared away by reloading that page. I don't want to see the old items cluttering up the space after we've seen them. 
2. They shouldn't come back with new items for on-screen display popups either, and if they are there, they should not be at the bottom pushing the newer things up and out of screen view.
3. Having that "Last 100 items" button back is useful for when needed.

The current changes have removed any benefit of using VH for me, aside from the style sheets, and should Amazon decide VH is something we shouldn't be using, for the sake of styling, it isn't worth the risk to use. I really appreciate all the work you have done with this extension. As it had been prior to these recent updates, it was an amazing tool for efficiency and I thank you! I'm sad that these updates have changed it so much. 

**Browser**
 Chrome on Linux, Brave on Linux, Kiwi on Android.

**Comment by FMaz008** [comment]
> "the next new items that arrive, the new items bring back old items"

This was the expected behavior of a quick patch to bring back the notifications after the switch to the new API but the catastrophic situation with the instant notifications.

Should be fixed with 2.9.9, just pending approval in the webstores. The notification monitor and pages should only show new notifications.

**Comment by urbanmoon** [comment]
Oh great! All that threw me into a tailspin and made me realize how much I rely on and appreciate VH - it's an immense help and thank you for making it! I'll watch for that release. Merci mille fois!
