### ISSUE TITLE
Notification Monitor Not Working / country code is not getting set upon vine page being loaded.

### ISSUE THREAD

**Issue by lmm268** [FMaz008/VineHelper#136]
The notification monitor isn't pulling info.  

Most recent item: Wed Dec 31 1969 18:00:00 GMT-0600 (Central Standard Time) and does not change.

Filter By dropdown does not change the outcome.  Screen stays blank.

Using Amazon Vine Helper US, open Vine Helper Version 2.9.9. Click on Notification Monitor. New screen opens and no notifications post regardless of the dropdown selected.

Notifications Monitor should show when new items drop. When Zero ETV is selected, new items with Zero ETV should be highlighted and show. KW dropdown should highlight items from KW list.

No errors listed in console.

Chrome Browser
![Screenshot 2024-10-02 203406](https://github.com/user-attachments/assets/336e66fc-200f-4db7-bf33-656a93d646f8)

**Comment by FMaz008** [comment]
Do you see the little spinning wheel at the bottom right corner showing up every 20 to 30 seconds ?
Under the network tab of the developer's console, do you see requests to api.vinehelper.ovh ? Are they status code 200?

**Comment by lmm268** [comment]
No, the spinning wheel does not appear at the bottom like it used to.


    On Thursday, October 3, 2024 at 04:20:24 AM CDT, Francois Mazerolle ***@***.***> wrote:  
 
 


Do you see the little spinning wheel at the bottom right corner showing up every 20 to 30 seconds ?
Under the network tab of the developer's console, do you see requests to api.vinehelper.ovh ? Are they status code 200?

**Comment by lmm268** [comment]
"error":"JSON format does not specify country"} shows up in the response. If it's updated to US for instance, it works

**Comment by FMaz008** [comment]
> "error":"JSON format does not specify country"} shows up in the response. If it's updated to US for instance, it works

Ok that extremely helpful. What is the payload/request look like? (don't forget to redact your UUID)

**Comment by lmm268** [comment]
- {"api_version":5,"country":null,"action":"get_latest_notifications","uuid":"                             "}   



    On Thursday, October 3, 2024 at 06:13:10 AM CDT, Francois Mazerolle ***@***.***> wrote:  
 
 



"error":"JSON format does not specify country"} shows up in the response. If it's updated to US for instance, it works


Ok that extremely helpful. What is the payload/request look like? (don't forget to redact your UUID)

**Comment by FMaz008** [comment]
Your country should not be null.
What amazon country are you using?
Have you tried refreshing a vine page so it can pick up the country and tried again ?
Is your status indicator green or red ? (Should be red)

**Comment by lmm268** [comment]
I'm not understanding where the status indicator is or where I should be looking.
I have tried refreshing Vine pages but it doesn't pick up the country. I am in the US

    On Thursday, October 3, 2024 at 06:30:16 AM CDT, Francois Mazerolle ***@***.***> wrote:  
 
 


Your country should not be null.
What amazon country are you using?
Have you tried refreshing a vine page so it can pick up the country and tried again ?
Is your status indicator green or red ? (Should be red)

**Comment by FMaz008** [comment]
When you refresh a vine page, do you then get an error in the developer's console that would prevent the code from executing properly and pick up your country?

**Comment by lmm268** [comment]
On Thursday, October 3, 2024 at 06:59:37 AM CDT, Francois Mazerolle ***@***.***> wrote:  
 
 


When you refresh a vine page, do you then get an error in the developer's console that would prevent the code from executing properly and pick up your country?

**Comment by lmm268** [comment]
![Screenshot 2024-10-03 070340](https://github.com/user-attachments/assets/6ba2eef5-cb94-4390-8ecd-5cb32878b7a0)

**Comment by FMaz008** [comment]
You're in the wrong tag. Click the Console tab and you should see a lot more (Amazon naturally generate a lot) :)

**Comment by lmm268** [comment]
The Console tab is empty



    On Thursday, October 3, 2024 at 12:49:51 PM CDT, Francois Mazerolle ***@***.***> wrote:  
 
 


You're in the wrong tab. Click the Console tab and you should see a lot more (Amazon naturally generate a lot) :)

**Comment by lmm268** [comment]
![image](https://github.com/user-attachments/assets/6aaf77bf-d162-48bd-a9d0-49e8d042b5cf)

**Comment by FMaz008** [comment]
In the "\/ Top" drop down, if you select Vine Helper, and then type in the console: `vineCountry`, what value do you get ?

**Comment by lmm268** [comment]
![image](https://github.com/user-attachments/assets/f6ecb701-3ccd-41e7-b41c-4befbafcbd89)

**Comment by FMaz008** [comment]
Why does it say no item selected in the drop down?

**Comment by lmm268** [comment]
This is all that shows up in my drop down

![image](https://github.com/user-attachments/assets/aa92877a-8048-49a9-95f5-909e258fbf7b)

If I select the bottom one, it changes to no item after a little bit

**Comment by FMaz008** [comment]
What's the URL of the page you are on? Because the extension is not running on that page.

**Comment by FMaz008** [comment]
Did you allow the extension's permissions?

**Comment by lmm268** [comment]
Yes, I allowed permissions. URL of the Vine helper extension or Vine URL?

**Comment by FMaz008** [comment]
The URL of the page you are refreshing with the developer's console open that:
- gives no error in the console tab and 
- does not detect Vine Helper Extension as a context in the drop down menu.

**Comment by FMaz008** [comment]
Closed as insufficiant details.

Seems like the extension is not running on the page you provided debug info.

If you still have the issues despite the latest updates (v2.10.4 is the current), please reopen
