### ISSUE TITLE
Manifest Refers to Non-Existent Files (case mismatch)

### ISSUE THREAD

**Issue by limitedAtonement** [FMaz008/VineHelper#137]
**Describe the bug**
`manifest*.json` refers to `Grid.js`, etc. but the files are actually `grid.js`, etc.

**To Reproduce**
0. Visit `chrome://extensions`
1. Click "Load unpacked"
2. Select the `dist` directory for the extension

**Expected behavior**
The extension is added to chromium

**(optional) Screenshots**

What actually happens:

![image](https://github.com/user-attachments/assets/bc905faf-9dff-4114-ae74-55733f0819a8)

**(optional) Error in the developer console**
None.

**(optional) Last page of Vine Helper debug log**
Not applicable

**Browser**
`chromium --version` says, `Chromium 129.0.6668.70 Arch Linux`
 
**Additional context**
None

**Comment by FMaz008** [comment]
That was a bug of v2.9.4, just update and it should be fixed. :)

**Comment by limitedAtonement** [comment]
I'm seeing the problem on `origin/main` (eca84c3).

**Comment by FMaz008** [comment]
Ah I see you are running the github code. Yeah, locally the files were named properly but git did not recognized the capitalization change. I just forced renamed the files and pushed commit 263055f5ed3fc8133d32d68b63559a7b804eba8e to fix the issue.

Is it working better for you now?

**Comment by limitedAtonement** [comment]
Yup! Reloaded without issue. Thank you!
