### ISSUE TITLE
`saveSettings` in `bootloader.js` not Defined

### ISSUE THREAD

**Issue by limitedAtonement** [FMaz008/VineHelper#139]
https://github.com/FMaz008/VineHelper/blob/263055/scripts/bootloader.js#L147 makes reference to a `saveSettings` function that doesn't appear to be defined. It's reported as an error in `chrome://extensions`:

![image](https://github.com/user-attachments/assets/8d76fa78-fa1a-4c8f-ba41-10a5e804a4f8)

**Comment by FMaz008** [comment]
Yeah that line needs to go. The new SettingMgr handle the saving directly from the .set() method. Odd I never notice the warning.

**Comment by FMaz008** [comment]
Fixed and pushed 63ae62fceddfd2b6582d8b805ae4426f3f03b72c . Thank you again for your straight to the point bug reports, makes it very easy to fix! :)
