### ISSUE TITLE
[Feature Request]: put highlight items at the top

### ISSUE THREAD

**Issue by Wladefant** [FMaz008/VineHelper#146]
### Feature Description

It can either be a mode where only the highlight keywords are only visible and the rest is hidden or just put highlights at the top and the rest after it

**Comment by FMaz008** [comment]
At the top of what?

**Comment by Wladefant** [comment]
Sorry, at the top of each page, when we are going through the pages, each page has items that match the keywoards, it would make sense to put them at the top so that you can look at them and go to the next page

**Comment by FMaz008** [comment]
Yeah I can do that :)

**Comment by FMaz008** [comment]
44566515bb2ec0e288244e3fe603113cdb25eece
