### ISSUE TITLE
Notification monitor: No longer able to manually load last 100 items

### ISSUE THREAD

**Issue by dynAdZ** [FMaz008/VineHelper#150]
### Bug Description

Since one of the last updates, the button to manually re-load the last 100 items is not available anymore.

### Steps to Reproduce

Open the notification monitor: The button that used to be at the bottom of the page is not there anymore.

### Expected Behavior

It was super helpful to pull the last couple of items manually, like when the browser is opened from scratch or the page was reloaded. All items are purged from the monitor in this case and it was therefore very helpful to be able to pull the last couple of items by using this button.

**Comment by FMaz008** [comment]
Not a bug. That button was abused and was removed.it is still available if you use Instant notifications (as the reason for abusing it is gone if you have that option enabled)

**Comment by dynAdZ** [comment]
I see, thanks for the explanation. I read through some Reddit articles and understood the problematic matter. However, any information on how to use this together with instant notifications? I did enable it but couldn't detect any change though. Thanks in advance!

**Comment by FMaz008** [comment]
What version are you running?
What changes were you expecting to see that you don't see ?
What country are you from (amazon.com?)

**Comment by dynAdZ** [comment]
I'm using 2.9.11 with Chrome 129. I mean you said it would somehow be possible to manually fetch the last couple of items with the experimental feature "instant notifications" turned on. However, I don't really get how it's possible.

**Comment by FMaz008** [comment]
It was added as of v2.9.12, but the latest release is 2.9.14.

Sorry for the confusion, it's been a busy week since we had a rocky start with the new API.

**Comment by dynAdZ** [comment]
This works, thank you so much for the swift reply. Keep up the awesome work!
