### ISSUE TITLE
[Enhancement]: the hide and pin icons are too dark

### ISSUE THREAD

**Issue by Wladefant** [FMaz008/VineHelper#151]
### Feature Description

the notifications monitor is dark and therefore it makes sense to make them white instead 
![image](https://github.com/user-attachments/assets/bdbdb52d-1eb1-48cd-ac50-1daef2094c34)

**Comment by FMaz008** [comment]
It's dark because you use your system in dark mode, night mode in the browser or a dark mode extension?

This might be a CSS issue, I'll try to figure it out.

**Comment by FMaz008** [comment]
Ok I figured it out. Will be fixed in the next version.

**Comment by FMaz008** [comment]
2.10.4 released
