### ISSUE TITLE
[Bug]: Fetch all elemnts does not work on android

### ISSUE THREAD

**Issue by Wladefant** [FMaz008/VineHelper#152]
### Bug Description

using yandex I am able to install the extension easily but there are a bunch of problems including missing fetch

### Steps to Reproduce

Missing elements
1. fetch all elements 

### Expected Behavior

working notifications monitor

### Screenshots (optional)

![SmartSelect_20241009_184154_Browser](https://github.com/user-attachments/assets/fd146500-5c2e-4048-87f7-4045b603f94c)

### Browser

Yandex Android Browser

### Additional Context

I have tried both the experimental instant notifications feature and without it. And it does not seem to work. Why is fetch 100 elements missing though?

**Comment by Wladefant** [comment]
I have just read some threads and the notifications monitor seems to be a working feature on android. To describe the yandex browser: it is based on chromium, the biggest browser on the russian internet and multiple other countries. 

What we definitely should implement is a feature where the site asks for notifications. I dont know whether that is possible because this is not a site but rather an internal url chrome-extension://jlglbhebbkfjcofdplbkanckkipkgfle/page/notifications.html

**Comment by FMaz008** [comment]
The Fetch Last 100 items was removed following abuse as people would use it repetitively to try to get notifications faster.

It has been removed from the old style "batch notifications", but is available if you use the new Instant Notification system as there is no more reason to abuse it with the instant notifications.

You can activate the Instant notification from the General tab under the experimental section.

The next release will default the notifications to Instant Notification and move the choice of the 2 system in the Notification tab.

**Comment by FMaz008** [comment]
What do you mean by "the site ask for notifications"? (I don't understand what feature you are suggesting.)

**Comment by Wladefant** [comment]
![SmartSelect_20241009_190524_Browser](https://github.com/user-attachments/assets/fc6cad34-40e6-4b98-94fc-d33c58093932)
with it does not seem to be able to connect to the server

**Comment by FMaz008** [comment]
Did you enabled the notifications in the Notification tab?

**Comment by Wladefant** [comment]
yes, I just installed the extension on firefox and same thing. You mean enable notification as in permission for the app ?

**Comment by FMaz008** [comment]
Go in Vine Helper's settings, and go in the Notifications tab. First checkbox there to enable the notifications.

**Comment by Wladefant** [comment]
my mistake and notification push works quite well too, nice... Although I would prefer I think if I open the Notification Monitor that either a popup like this appears or something similar or just a toggle in the on the notifications.html page
