### ISSUE TITLE
[Bug]: Notifications Monitor Not Working You need to Reload the Extension after update to 2.10.1

### ISSUE THREAD

**Issue by JeramieG-IDG** [FMaz008/VineHelper#154]
### Bug Description

I've been running 2.9.x fine for about 2 weeks and loving it.  about 30 minutes ago i restarted my computer and when i went back into chrome I was exxcited to see that vh 2.10.1 had been installed.  Everything seems good except that Notification Monitor doesn't work.  It says Server status:  OFF Not working, you need to reload the extension.

### Steps to Reproduce

1 Started Chrome
2 Went to amazon vine
3 Clicked the new [VH Notifications Monitor] link on the vine menu
4 Notifications monitor opens but doesn't update.

### Expected Behavior

it has always connected fine and updated in the past.

### Screenshots (optional)

![image](https://github.com/user-attachments/assets/592540ec-65ef-49fd-b5ad-fb5074cb928f)

### Error in Developer Console (optional)

No errors or anything else in the monitor tabs console.  Also, when i click to load the latest 100 nothing happens in the network tab either.
![Uploading image.png…]()

### Last Page of Debug Log (optional)

Vine Helper - DebuggerX
[
2ms: HIDDENMGR: Loading list
3ms: PINNEDMGR: Loading list
4ms: PREBOOT: Waiting on config to be loaded...
77ms: HIDDENMGR: List loaded.
77ms: PINNEDMGR: List loaded.
491ms: TEMPLATE: Loaded template view/notification_container.html from memory.
871ms: BOOT: Booterloader starting. DOM load time from Amazon: 871ms
871ms: BOOT: Waiting on preboot to complete...
1706ms: PREBOOT: config loaded!
1707ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/small-items.css from file.
1718ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/remove-header.css from file.
1719ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/remove-footer.css from file.
1719ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/remove-associate-header.css from file.
1719ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/more-description-text.css from file.
1720ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/dark-theme.css from file.
1720ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/etv-modal-on-top.css from file.
1720ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/pagination-on-top.css from file.
1721ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/collapsable-categories.css from file.
1721ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/limited-quantity-icon.css from file.
1722ms: TEMPLATE: Loading template node_modules/vine-styling/desktop/rfy-afa-ai-tabs.css from file.
1722ms: PREBOOT: Thorvarium stylesheets injected
1722ms: PREBOOT: Thorvarium country-specific stylesheets injected
1722ms: PREBOOT: Preboot routine completed.
1723ms: BOOT: Config available. Begining init() function
1733ms: FETCH: Fetching data from VineHelper's server...
1736ms: BOOT: Script injected
1736ms: BOOT: Creating tabs system
1737ms: TEMPLATE: Loading template view/tabs.html from file.
1930ms: BOOT: Opts data obtained from inj.js.
2323ms: TEMPLATE: Loading template view/widget_hideall.html from file.
2363ms: FETCH: Response received from VineHelper's server...630ms
2363ms: FETCH: Waiting on hidden items list to be loaded...
2363ms: FETCH: Hidden items list loaded...
2363ms: FETCH: Waiting toolbars to be drawn...
2371ms: BOOT: Grid system completed
2372ms: TEMPLATE: Loading template view/bookmark.html from file.
2408ms: DRAW: Creating #vh-toolbar-B0CT3DVG84
2408ms: TEMPLATE: Loading template view/toolbar.html from file.
2494ms: DRAW: Creating #vh-toolbar-B0CT4S6682
2494ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2496ms: DRAW: Creating #vh-toolbar-B0CTC1HB62
2496ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2498ms: DRAW: Creating #vh-toolbar-B0CTG842QS
2498ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2498ms: DRAW: Creating #vh-toolbar-B0CTKGVLY7
2498ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2498ms: DRAW: Creating #vh-toolbar-B0CTQQQ6X5
2499ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2499ms: DRAW: Creating #vh-toolbar-B0CTSZ447J
2499ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2500ms: DRAW: Creating #vh-toolbar-B0CTT6WGJ7
2500ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2501ms: DRAW: Creating #vh-toolbar-B0CTTSNL16
2501ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2502ms: DRAW: Creating #vh-toolbar-B0CTTW4X7K
2502ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2502ms: DRAW: Creating #vh-toolbar-B0CV4L5Q8V
2502ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2503ms: DRAW: Creating #vh-toolbar-B0CV4RPHTJ
2503ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2503ms: DRAW: Creating #vh-toolbar-B0CVHHKS9M
2503ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2504ms: DRAW: Creating #vh-toolbar-B0CVS26YT7
2504ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2505ms: DRAW: Creating #vh-toolbar-B0CVZZHQTD
2505ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2505ms: DRAW: Creating #vh-toolbar-B0CW5PHNHH
2505ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2505ms: DRAW: Creating #vh-toolbar-B0CW67BN8H
2505ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2506ms: DRAW: Creating #vh-toolbar-B0CW68TZFK
2506ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2506ms: DRAW: Creating #vh-toolbar-B0CW9G5883
2506ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2506ms: DRAW: Creating #vh-toolbar-B0CWF28TR6
2506ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2507ms: DRAW: Creating #vh-toolbar-B0CWKDQGFP
2507ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2508ms: DRAW: Creating #vh-toolbar-B0CWNQDSPD
2508ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2508ms: DRAW: Creating #vh-toolbar-B0CWNSKV6P
2508ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2509ms: DRAW: Creating #vh-toolbar-B0CWNSL5GR
2509ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2509ms: DRAW: Creating #vh-toolbar-B0CWPKMTVV
2509ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2510ms: DRAW: Creating #vh-toolbar-B0CWPT5JY7
2510ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2510ms: DRAW: Creating #vh-toolbar-B0CWTJXKM9
2510ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2510ms: DRAW: Creating #vh-toolbar-B0CWVMRBDW
2510ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2511ms: DRAW: Creating #vh-toolbar-B0CX3FXSX5
2511ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2511ms: DRAW: Creating #vh-toolbar-B0CX539BRD
2511ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2511ms: DRAW: Creating #vh-toolbar-B0CX56962H
2511ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2512ms: DRAW: Creating #vh-toolbar-B0CX57P65J
2512ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2513ms: DRAW: Creating #vh-toolbar-B0CX59H5Q6
2513ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2514ms: DRAW: Creating #vh-toolbar-B0CX8LNS5R
2514ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2515ms: DRAW: Creating #vh-toolbar-B0CX8V2TMC
2515ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2515ms: DRAW: Creating #vh-toolbar-B0CX8WYBVM
2515ms: TEMPLATE: Loaded template view/toolbar.html from memory.
2515ms: done creating toolbars.
2905ms: FETCH: Interface loaded, processing fetch data...
2905ms: DRAW: Processing ASIN #B0CT3DVG84
2905ms: DRAW: Setting ETV
2909ms: DRAW: Setting Date
2909ms: DRAW: Setting orders
2909ms: DRAW: A
2909ms: DRAW: Updating the toolbar
2909ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CT3DVG84
2909ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2909ms: DRAW-UPDATE-TOOLBAR: Create order widget
2910ms: TEMPLATE: Loading template view/widget_order.html from file.
2910ms: DRAW: Done updating the toolbar
2912ms: DRAW: Processing ASIN #B0CT4S6682
2912ms: DRAW: Setting Date
2912ms: DRAW: Setting orders
2912ms: DRAW: A
2912ms: DRAW: Updating the toolbar
2912ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CT4S6682
2912ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2912ms: DRAW-UPDATE-TOOLBAR: Create order widget
2912ms: TEMPLATE: Loading template view/widget_order.html from file.
2913ms: DRAW: Done updating the toolbar
2913ms: DRAW: Processing ASIN #B0CTC1HB62
2913ms: DRAW: Setting ETV
2917ms: DRAW: Setting Date
2917ms: DRAW: Setting orders
2917ms: DRAW: A
2917ms: DRAW: Updating the toolbar
2917ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTC1HB62
2917ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2917ms: DRAW-UPDATE-TOOLBAR: Create order widget
2917ms: TEMPLATE: Loading template view/widget_order.html from file.
2918ms: DRAW: Done updating the toolbar
2919ms: DRAW: Processing ASIN #B0CTG842QS
2919ms: DRAW: Setting Date
2919ms: DRAW: Setting orders
2919ms: DRAW: A
2919ms: DRAW: Updating the toolbar
2919ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTG842QS
2919ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2919ms: DRAW-UPDATE-TOOLBAR: Create order widget
2919ms: TEMPLATE: Loading template view/widget_order.html from file.
2919ms: DRAW: Done updating the toolbar
2921ms: DRAW: Processing ASIN #B0CTKGVLY7
2921ms: DRAW: Setting Date
2921ms: DRAW: Setting orders
2921ms: DRAW: A
2921ms: DRAW: Updating the toolbar
2921ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTKGVLY7
2921ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2921ms: DRAW-UPDATE-TOOLBAR: Create order widget
2922ms: TEMPLATE: Loading template view/widget_order.html from file.
2922ms: DRAW: Done updating the toolbar
2922ms: DRAW: Processing ASIN #B0CTQQQ6X5
2922ms: DRAW: Setting Date
2923ms: TILE: The item is more recent than the time marker, highlight it.
2923ms: DRAW: Setting orders
2923ms: DRAW: A
2923ms: DRAW: Updating the toolbar
2923ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTQQQ6X5
2923ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2923ms: DRAW-UPDATE-TOOLBAR: Create order widget
2923ms: TEMPLATE: Loading template view/widget_order.html from file.
2923ms: DRAW: Done updating the toolbar
2924ms: DRAW: Processing ASIN #B0CTSZ447J
2924ms: DRAW: Setting ETV
2925ms: DRAW: Setting Date
2926ms: DRAW: Setting orders
2926ms: DRAW: A
2926ms: DRAW: Updating the toolbar
2926ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTSZ447J
2926ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2926ms: DRAW-UPDATE-TOOLBAR: Create order widget
2926ms: TEMPLATE: Loading template view/widget_order.html from file.
2926ms: DRAW: Done updating the toolbar
2927ms: DRAW: Processing ASIN #B0CTT6WGJ7
2927ms: DRAW: Setting ETV
2928ms: DRAW: Setting Date
2928ms: DRAW: Setting orders
2928ms: DRAW: A
2928ms: DRAW: Updating the toolbar
2928ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTT6WGJ7
2928ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2928ms: DRAW-UPDATE-TOOLBAR: Create order widget
2928ms: TEMPLATE: Loading template view/widget_order.html from file.
2928ms: DRAW: Done updating the toolbar
2931ms: DRAW: Processing ASIN #B0CTTSNL16
2931ms: DRAW: Setting Date
2931ms: DRAW: Setting orders
2931ms: DRAW: A
2931ms: DRAW: Updating the toolbar
2931ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTTSNL16
2931ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2931ms: DRAW-UPDATE-TOOLBAR: Create order widget
2931ms: TEMPLATE: Loading template view/widget_order.html from file.
2932ms: DRAW: Done updating the toolbar
2934ms: DRAW: Processing ASIN #B0CTTW4X7K
2934ms: DRAW: Setting ETV
2935ms: DRAW: Setting Date
2935ms: DRAW: Setting orders
2935ms: DRAW: A
2935ms: DRAW: Updating the toolbar
2935ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CTTW4X7K
2935ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2935ms: DRAW-UPDATE-TOOLBAR: Create order widget
2936ms: TEMPLATE: Loading template view/widget_order.html from file.
2936ms: DRAW: Done updating the toolbar
2937ms: DRAW: Processing ASIN #B0CV4L5Q8V
2937ms: DRAW: Setting Date
2937ms: DRAW: Setting orders
2937ms: DRAW: A
2937ms: DRAW: Updating the toolbar
2937ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CV4L5Q8V
2937ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2937ms: DRAW-UPDATE-TOOLBAR: Create order widget
2937ms: TEMPLATE: Loading template view/widget_order.html from file.
2937ms: DRAW: Done updating the toolbar
2938ms: DRAW: Processing ASIN #B0CV4RPHTJ
2938ms: DRAW: Setting ETV
2940ms: DRAW: Setting Date
2940ms: DRAW: Setting orders
2940ms: DRAW: A
2940ms: DRAW: Updating the toolbar
2940ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CV4RPHTJ
2940ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2940ms: DRAW-UPDATE-TOOLBAR: Create order widget
2940ms: TEMPLATE: Loading template view/widget_order.html from file.
2941ms: DRAW: Done updating the toolbar
2943ms: DRAW: Processing ASIN #B0CVHHKS9M
2943ms: DRAW: Setting ETV
2944ms: DRAW: Setting Date
2944ms: DRAW: Setting orders
2944ms: DRAW: A
2944ms: DRAW: Updating the toolbar
2944ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CVHHKS9M
2944ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2944ms: DRAW-UPDATE-TOOLBAR: Create order widget
2944ms: TEMPLATE: Loading template view/widget_order.html from file.
2945ms: DRAW: Done updating the toolbar
2945ms: DRAW: Processing ASIN #B0CVS26YT7
2945ms: DRAW: Setting ETV
2947ms: DRAW: Setting Date
2947ms: DRAW: Setting orders
2947ms: DRAW: A
2947ms: DRAW: Updating the toolbar
2947ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CVS26YT7
2947ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2947ms: DRAW-UPDATE-TOOLBAR: Create order widget
2947ms: TEMPLATE: Loading template view/widget_order.html from file.
2947ms: DRAW: Done updating the toolbar
2952ms: DRAW: Processing ASIN #B0CVZZHQTD
2952ms: DRAW: Setting ETV
2953ms: DRAW: Setting Date
2954ms: DRAW: Setting orders
2954ms: DRAW: A
2954ms: DRAW: Updating the toolbar
2954ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CVZZHQTD
2954ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2954ms: DRAW-UPDATE-TOOLBAR: Create order widget
2954ms: TEMPLATE: Loading template view/widget_order.html from file.
2954ms: DRAW: Done updating the toolbar
2955ms: DRAW: Processing ASIN #B0CW5PHNHH
2955ms: DRAW: Setting Date
2955ms: DRAW: Setting orders
2955ms: DRAW: A
2955ms: DRAW: Updating the toolbar
2955ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CW5PHNHH
2955ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2955ms: DRAW-UPDATE-TOOLBAR: Create order widget
2955ms: TEMPLATE: Loading template view/widget_order.html from file.
2957ms: DRAW: Done updating the toolbar
2961ms: DRAW: Processing ASIN #B0CW67BN8H
2961ms: DRAW: Setting ETV
2962ms: DRAW: Setting Date
2962ms: DRAW: Setting orders
2962ms: DRAW: A
2962ms: DRAW: Updating the toolbar
2962ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CW67BN8H
2962ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2962ms: DRAW-UPDATE-TOOLBAR: Create order widget
2962ms: TEMPLATE: Loading template view/widget_order.html from file.
2965ms: DRAW: Done updating the toolbar
2965ms: DRAW: Processing ASIN #B0CW68TZFK
2965ms: DRAW: Setting Date
2966ms: DRAW: Setting orders
2966ms: DRAW: A
2966ms: DRAW: Updating the toolbar
2966ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CW68TZFK
2966ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2966ms: DRAW-UPDATE-TOOLBAR: Create order widget
2966ms: TEMPLATE: Loading template view/widget_order.html from file.
2966ms: DRAW: Done updating the toolbar
2967ms: DRAW: Processing ASIN #B0CW9G5883
2967ms: DRAW: Setting ETV
2969ms: DRAW: Setting Date
2969ms: DRAW: Setting orders
2969ms: DRAW: A
2969ms: DRAW: Updating the toolbar
2969ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CW9G5883
2969ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2969ms: DRAW-UPDATE-TOOLBAR: Create order widget
2969ms: TEMPLATE: Loading template view/widget_order.html from file.
2969ms: DRAW: Done updating the toolbar
2972ms: DRAW: Processing ASIN #B0CWF28TR6
2972ms: DRAW: Setting ETV
2973ms: DRAW: Setting Date
2974ms: DRAW: Setting orders
2974ms: DRAW: A
2974ms: DRAW: Updating the toolbar
2974ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWF28TR6
2974ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2974ms: DRAW-UPDATE-TOOLBAR: Create order widget
2974ms: TEMPLATE: Loading template view/widget_order.html from file.
2974ms: DRAW: Done updating the toolbar
2975ms: DRAW: Processing ASIN #B0CWKDQGFP
2975ms: DRAW: Setting ETV
2983ms: DRAW: Setting Date
2984ms: DRAW: Setting orders
2984ms: DRAW: A
2984ms: DRAW: Updating the toolbar
2984ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWKDQGFP
2985ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2985ms: DRAW-UPDATE-TOOLBAR: Create order widget
2985ms: TEMPLATE: Loading template view/widget_order.html from file.
2985ms: DRAW: Done updating the toolbar
2986ms: DRAW: Processing ASIN #B0CWNQDSPD
2988ms: DRAW: Setting Date
2988ms: DRAW: Setting orders
2988ms: DRAW: A
2988ms: DRAW: Updating the toolbar
2988ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWNQDSPD
2988ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2988ms: DRAW-UPDATE-TOOLBAR: Create order widget
2988ms: TEMPLATE: Loading template view/widget_order.html from file.
2988ms: DRAW: Done updating the toolbar
2989ms: DRAW: Processing ASIN #B0CWNSKV6P
2989ms: DRAW: Setting ETV
2990ms: DRAW: Setting Date
2990ms: DRAW: Setting orders
2990ms: DRAW: A
2990ms: DRAW: Updating the toolbar
2990ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWNSKV6P
2991ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2991ms: DRAW-UPDATE-TOOLBAR: Create order widget
2991ms: TEMPLATE: Loading template view/widget_order.html from file.
2991ms: DRAW: Done updating the toolbar
2992ms: DRAW: Processing ASIN #B0CWNSL5GR
2992ms: DRAW: Setting ETV
2995ms: DRAW: Setting Date
2995ms: DRAW: Setting orders
2995ms: DRAW: A
2995ms: DRAW: Updating the toolbar
2995ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWNSL5GR
2995ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2996ms: DRAW-UPDATE-TOOLBAR: Create order widget
2996ms: TEMPLATE: Loading template view/widget_order.html from file.
2997ms: DRAW: Done updating the toolbar
2997ms: DRAW: Processing ASIN #B0CWPKMTVV
2997ms: DRAW: Setting ETV
2998ms: DRAW: Setting Date
2998ms: DRAW: Setting orders
2998ms: DRAW: A
2998ms: DRAW: Updating the toolbar
2998ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWPKMTVV
2998ms: DRAW-UPDATE-TOOLBAR: Setting icon status
2999ms: DRAW-UPDATE-TOOLBAR: Create order widget
2999ms: TEMPLATE: Loading template view/widget_order.html from file.
2999ms: DRAW: Done updating the toolbar
3003ms: DRAW: Processing ASIN #B0CWPT5JY7
3003ms: DRAW: Setting Date
3003ms: DRAW: Setting orders
3003ms: DRAW: A
3003ms: DRAW: Updating the toolbar
3003ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWPT5JY7
3004ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3004ms: DRAW-UPDATE-TOOLBAR: Create order widget
3004ms: TEMPLATE: Loading template view/widget_order.html from file.
3005ms: DRAW: Done updating the toolbar
3006ms: DRAW: Processing ASIN #B0CWTJXKM9
3006ms: DRAW: Setting Date
3007ms: DRAW: Setting orders
3007ms: DRAW: A
3007ms: DRAW: Updating the toolbar
3007ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWTJXKM9
3007ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3007ms: DRAW-UPDATE-TOOLBAR: Create order widget
3007ms: TEMPLATE: Loading template view/widget_order.html from file.
3011ms: DRAW: Done updating the toolbar
3014ms: DRAW: Processing ASIN #B0CWVMRBDW
3014ms: DRAW: Setting Date
3014ms: DRAW: Setting orders
3014ms: DRAW: A
3014ms: DRAW: Updating the toolbar
3014ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CWVMRBDW
3014ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3014ms: DRAW-UPDATE-TOOLBAR: Create order widget
3014ms: TEMPLATE: Loading template view/widget_order.html from file.
3015ms: DRAW: Done updating the toolbar
3016ms: DRAW: Processing ASIN #B0CX3FXSX5
3018ms: DRAW: Setting Date
3018ms: DRAW: Setting orders
3018ms: DRAW: A
3018ms: DRAW: Updating the toolbar
3018ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX3FXSX5
3018ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3018ms: DRAW-UPDATE-TOOLBAR: Create order widget
3018ms: TEMPLATE: Loading template view/widget_order.html from file.
3018ms: DRAW: Done updating the toolbar
3019ms: DRAW: Processing ASIN #B0CX539BRD
3019ms: DRAW: Setting ETV
3020ms: DRAW: Setting Date
3020ms: DRAW: Setting orders
3020ms: DRAW: A
3020ms: DRAW: Updating the toolbar
3020ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX539BRD
3020ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3020ms: DRAW-UPDATE-TOOLBAR: Create order widget
3020ms: TEMPLATE: Loading template view/widget_order.html from file.
3020ms: DRAW: Done updating the toolbar
3023ms: DRAW: Processing ASIN #B0CX56962H
3023ms: DRAW: Setting ETV
3025ms: DRAW: Setting Date
3025ms: DRAW: Setting orders
3025ms: DRAW: A
3025ms: DRAW: Updating the toolbar
3025ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX56962H
3025ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3025ms: DRAW-UPDATE-TOOLBAR: Create order widget
3025ms: TEMPLATE: Loading template view/widget_order.html from file.
3026ms: DRAW: Done updating the toolbar
3026ms: DRAW: Processing ASIN #B0CX57P65J
3026ms: DRAW: Setting Date
3027ms: DRAW: Setting orders
3027ms: DRAW: A
3027ms: DRAW: Updating the toolbar
3027ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX57P65J
3027ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3027ms: DRAW-UPDATE-TOOLBAR: Create order widget
3028ms: TEMPLATE: Loading template view/widget_order.html from file.
3028ms: DRAW: Done updating the toolbar
3029ms: DRAW: Processing ASIN #B0CX59H5Q6
3029ms: DRAW: Setting ETV
3030ms: DRAW: Setting Date
3030ms: DRAW: Setting orders
3030ms: DRAW: A
3030ms: DRAW: Updating the toolbar
3030ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX59H5Q6
3030ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3030ms: DRAW-UPDATE-TOOLBAR: Create order widget
3030ms: TEMPLATE: Loading template view/widget_order.html from file.
3030ms: DRAW: Done updating the toolbar
3035ms: DRAW: Processing ASIN #B0CX8LNS5R
3035ms: DRAW: Setting Date
3035ms: DRAW: Setting orders
3035ms: DRAW: A
3035ms: DRAW: Updating the toolbar
3035ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX8LNS5R
3035ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3035ms: DRAW-UPDATE-TOOLBAR: Create order widget
3035ms: TEMPLATE: Loading template view/widget_order.html from file.
3036ms: DRAW: Done updating the toolbar
3036ms: DRAW: Processing ASIN #B0CX8V2TMC
3036ms: DRAW: Setting ETV
3038ms: DRAW: Setting Date
3038ms: DRAW: Setting orders
3038ms: DRAW: A
3038ms: DRAW: Updating the toolbar
3038ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX8V2TMC
3038ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3038ms: DRAW-UPDATE-TOOLBAR: Create order widget
3038ms: TEMPLATE: Loading template view/widget_order.html from file.
3038ms: DRAW: Done updating the toolbar
3041ms: DRAW: Processing ASIN #B0CX8WYBVM
3041ms: DRAW: Setting ETV
3042ms: DRAW: Setting Date
3043ms: DRAW: Setting orders
3043ms: DRAW: A
3043ms: DRAW: Updating the toolbar
3043ms: DRAW-UPDATE-TOOLBAR: Updating #vh-toolbar-B0CX8WYBVM
3043ms: DRAW-UPDATE-TOOLBAR: Setting icon status
3043ms: DRAW-UPDATE-TOOLBAR: Create order widget
3043ms: TEMPLATE: Loading template view/widget_order.html from file.
3044ms: DRAW: Done updating the toolbar
3045ms: DRAW: Loading remote pinned products
3045ms: Done updating products
711293ms: Storage used by arrTemplate: 41.9 KB representing 9 items
711295ms: Storage used by hiddenItems: 7.16 KB representing 282 items
711296ms: Storage used by settings: 1.68 KB
711296ms: TEMPLATE: Loading template view/modal.html from file.
737965ms: Storage used by arrTemplate: 108.64 KB representing 64 items
737966ms: Storage used by hiddenItems: 7.16 KB representing 282 items
737967ms: Storage used by settings: 1.68 KB

]

### Browser

Chrome is up to date Version 129.0.6668.101 (Official Build) (64-bit)

**Comment by FMaz008** [comment]
Faulty build, a new version has been published to fix the issue. Updating the extension should fix the issue. Re-open the ticket if you are still having problems with 2.10.4

**Comment by Wladefant** [comment]
Still an isssue, service worker connecting and disconnecting: 

Sure! Here’s the output in a hidden markdown code block:

<details>
<summary>Click to view the console</summary>

```
vh_service_worker.js:154 
 Event handler of 'offline' event must be added on the initial evaluation of worker script.

WS Connected
vh_service_worker.js:201 WS Disconnected
vh_service_worker.js:165 WS Connected
vh_service_worker.js:201 WS Disconnected
vh_service_worker.js:165 WS Connected
vh_service_worker.js:201 WS Disconnected
```

</details>

**Comment by FMaz008** [comment]
We reached the hard cap of 200 simultaneous connection server side! 

I raised the limit to 10k, should be working without any action on your part.

**Comment by Wladefant** [comment]
works
