### ISSUE TITLE
[Question]: Did the fetch button go away?

### ISSUE THREAD

**Issue by jairov96** [FMaz008/VineHelper#155]
### Feature Description

![image](https://github.com/user-attachments/assets/a59c4843-2d13-4d9d-b9f7-9f8b8598a8fd)

I noticed the fetch button has been commented, it was an extremely useful feature to have! Is it coming back any time soon?

Cheers and great work! Let me know if there's any way to donate.

**Comment by FMaz008** [comment]
I suspect you are using an old version.
It was temporarily removed while I was getting the instant notifications to work.

Instant notifications are in place now and if you use them, the fetch last 100 button is there.

**Comment by jairov96** [comment]
You're completely correct, chrome still had me and version 9.x!

Also, just send some cash :) 

Cheers!
