### ISSUE TITLE
[Bug]: "Auto-hide items keywords" not taking effect

### ISSUE THREAD

**Issue by 1920x1200** [FMaz008/VineHelper#159]
### Bug Description

When I filter notifications by Zero ETV only, I'm getting alerts for keywords I've set to auto hide

### Steps to Reproduce

1. Put keywords in "Auto-hide items keywords" such as "Nail, nail, Nails, nails" 
2. Open the notification monitor
3. Change notification monitor to filter by Zero ETV.
4. Wait a while and watch notifications start coming in for nail products even though I've set those to auto hide. 

### Expected Behavior

I should not see notifications/items that include keywords I've set to be hidden

### Screenshots (optional)

![Screenshot 2024-10-28 at 10 08 23 AM](https://github.com/user-attachments/assets/cce1466b-2aa8-4516-a485-87344e425706)
![Screenshot 2024-10-28 at 10 10 08 AM](https://github.com/user-attachments/assets/8aba6725-c31f-44c4-b5a1-77c5766458c0)

### Error in Developer Console (optional)

![Screenshot 2024-10-28 at 10 12 29 AM](https://github.com/user-attachments/assets/80179bfa-a20b-41e9-a685-3be403012b73)

### Browser

Firefox 131.0.3

### Additional Context

Vine Helper 2.10.6

**Comment by FMaz008** [comment]
Under the notification tab, do you have the option "Hide Notifications with auto-hide Keywords" enabled ?

Note: The 0ETV filter only mask/hide items which already exist in the notification monitor. If an item match the hide keyword list (and the option is enabled), it won't add it at all. Basically what I'm saying is that the 2 systems are totally independent and you should see the same issue regardless of the filter option you pick.

**Comment by 1920x1200** [comment]
Thanks for the fast response. I don't know how, but that setting got unchecked! Once I checked it again, the issue is resolved. Sorry for the false bug report. Please close this out. Thanks!
