### ISSUE TITLE
New items display incorrect First Seen

### ISSUE THREAD

**Issue by crysallis** [FMaz008/VineHelper#18]
Items are showing "First seen: -61201 secs ago" when they are new
![image](https://github.com/FMaz008/VineHelper/assets/906727/54c07e7e-c7ac-48a3-b17c-a162f55ec219)

**Comment by sorphin** [comment]
Have this issue too..
<img width="260" alt="Screen Shot 2024-01-30 at 4 18 35 PM" src="https://github.com/FMaz008/VineHelper/assets/496131/38425d6b-773c-4299-81e1-8d7a95af40de">

**Comment by FMaz008** [comment]
What version are you using?

**Comment by sorphin** [comment]
> What version are you using?

I repulled earlier today after you fixed my bug(s) for reference.
   6ae7bdf..f55492a  main       -> origin/main

**Comment by crysallis** [comment]
Running 1.19 and pulled 1.20 but that seems to have fixed itself? lol I refreshed again after trying to dig in to the cause and now it's no longer happening

**Comment by FMaz008** [comment]
1.19 definitely had an issue with comparing the server time to the browser time, which worked fine for me but not for people on a different timezone.

@sorphin seems to suggest it was still an issue with the latest code. Which I'm puzzled, but I just pushed an new version that should be simplified in case javascript was not doing good comparing formatted dates, now it's comparing timestamps.

Let me know if this is better.

Note that the bookmark will need to be reset if you had one saved.

**Comment by crysallis** [comment]
I was seeing in both the 1.19 published version on the pulled 1.20 code, but I do not see it now... so that's confusing... but I'll keep looking

**Comment by sorphin** [comment]
Just repulled a few ago. Will let you know next time i see something new appear...

**Comment by sorphin** [comment]
Seems to be ok for me now. I repulled this morning too.

**Comment by FMaz008** [comment]
Will leave it open for 24hrs and close it if fixed.

**Comment by FMaz008** [comment]
No further reports from >=v.1.20
