### ISSUE TITLE
Remote Hidden Syncing

### ISSUE THREAD

**Issue by LongDono** [FMaz008/VineHelper#21]
What is the proper method for someone to implement the remote syncing?

I copied the GUID from my desktop to my phone's browser. As they were not synced, I realized I'd failed to enable syncing on the notebook, and after doing so, checked the phone again, which was still not synced (I refreshed the page).

Thinking it was a bad idea and that it might overwrite my notebook's hidden items, I also enabled syncing on my phone. When I came back to it later on my notebook, sure enough, all of my hidden items were gone, and everything was unhidden again.  If you are wondering how many I had hidden, I've gone through everything that is currently in Vine...

I guess my issue is, what was the correct way to have done this? :) How does the code know to import the items from the server vs overwrite what is already there?

**Comment by FMaz008** [comment]
Sounds like you set it up properly. You want both devices to share the same UUID. 

Syncing might not be the best choice of word as it's not uoloading pre-existing lists at this point. Once you activate the feature, It will begin saving the items on the server (as well as locally). But that's only for the item that you hide or show *after* the feature is enabled.

**Comment by LongDono** [comment]
Ahhhh. That makes more sense from your side of things. Is it normal that enabling it will unhide everything that was previously hidden during the change over to this process? Ideally, it would somehow not unhide everything and just continue to send newly hidden items to your SQL server...

**Comment by FMaz008** [comment]
> Is it normal that enabling it will unhide everything that was previously hidden during the change over to this process? 

The hidden server only store items that are to be hidden.
When enabling the feature, and there are no items stored remotely, absolutely nothing different will happen. The local list will decide what is hidden.

So, unless I messed up something, it is not possible that enabling the remote save "unhide" items. The remote server cannot remove anything from the local list, which is actually why I was saying it's not appropriate to call this feature a "sync". It does not touch the local list, it is actually a second step of hidding item.

When you hide, or show, an item, what happens first is that the local list is altered, then that request to have that item shown or hidden is submitted to the server where the item is saved (if hidden), or deleted (if shown)

**Comment by LongDono** [comment]
I see we are now on 2.0.6. Not sure if you changed something but I noticed today on my notebook that the previously hidden items are now properly showing up as hidden.
