### ISSUE TITLE
Unavailable appearing in Available Tab

### ISSUE THREAD

**Issue by LongDono** [FMaz008/VineHelper#22]
With the latest update, I sometimes see unavailable items in the Available tab:
![image](https://github.com/FMaz008/VineHelper/assets/5301311/e227423b-1230-4d93-a527-04b1cc29eb63)

Reloading the page makes them go away; if you don't reload, they will continue to appear on other pages.

**Comment by FMaz008** [comment]
In the options, what are your self discard and consensus discard set to?

**Comment by LongDono** [comment]
It's worse than I thought. What happens is, I navigate to the next page in the AI and:
1. The list appears but without the items I had hidden
2. The hidden items and the unavailable items reappear
3. Reloading that page then hides the unavailable items but the previously hidden (prior to remote syncing) items remain
4. This repeats on the next page, and the next, etc.

**Comment by LongDono** [comment]
![image](https://github.com/FMaz008/VineHelper/assets/5301311/967b64a7-0cde-4149-b308-6b000abc19c2)

**Comment by LongDono** [comment]
Interestingly, there are also items in Unavailable, and they are not the same, at least until refreshed.
![image](https://github.com/FMaz008/VineHelper/assets/5301311/a1a4da65-38f5-43fe-81b4-df8c3e944d43)
![image](https://github.com/FMaz008/VineHelper/assets/5301311/192b90d8-9d2a-4467-9449-582466383afb)

Once refreshed they're all together:
![image](https://github.com/FMaz008/VineHelper/assets/5301311/25e9e707-82ee-46fa-b2e8-8beddb0e3273)

**Comment by FMaz008** [comment]
Your refresh thing is very odd.
Vine Helper does not pull product out of its database. It's literally just modifying the existing items which are on the page, and moving them around.

Do you have some weird extension causing some caching issues ?

**Comment by LongDono** [comment]
I haven't changed any extensions since installing Vine Helper and I have very few: Just Rakuten, Bitwarden, Speed Dial 2, Keepa, and Homepage in a New Tab.

Curiously enough, unless you changed something in 2.0.6, this behavior is no longer occurring today.

**Comment by FMaz008** [comment]
I haven't changed anything specific to this issue, no. Same for 2.0.7.

BUT, there was a bug in the database that affected products with variant, where the parent asin (the one listed) would save with extra quotes.

But as far as I can tell this would only affect the products not showing ETV or order counts. Nothing to do with votes.

I'm not 100% certain on the actual scope and impact of that bad data though, so it could have been it in a way I do not understand yet.

**Comment by FMaz008** [comment]
Is this still an issue?

**Comment by LongDono** [comment]
No, this is no longer occurring.
