### ISSUE TITLE
[FR] Show publish to discord trumpet by default

### ISSUE THREAD

**Issue by legion0** [FMaz008/VineHelper#23]
Currently its hard to find the feature because it requires adding the API Key in the Brenda tab in the extension settings.

It would be much easier to discover if the trumpet was shown by default with a hover card instruction to go to the extension settings to add the API key to enable publish to discord.

This probably also means another option is needed to hide the trumpet for folks that aren't interested in that feature and don't want to see the grayed out trumpet there forever.

**Comment by FMaz008** [comment]
While it's true that is would probably drive more people to the Discord and to use the feature, 
I don't think it's a good idea to show a button for a feature that's not enabled. It could quickly become cluttered. 

I'm on the fence about this idea. Maybe bring it forward to discord see what people think...
