### ISSUE TITLE
[FR] Change window title to match search query

### ISSUE THREAD

**Issue by legion0** [FMaz008/VineHelper#24]
I use bookmarks to manage some saved searches and it is rather annoying that the page title is always `Amazon Vine`. It would be much nicer if the title was `Amazon Vine - <Search Query>`.
This could be a nice feature for the extension and sounds like it should be simple to implement.

Note that this is also helpful for regular tabs, not just bookmarks.

**Comment by FMaz008** [comment]
I think it would be doable. Just monitor the URL for the search query and update the title of the page.

**Comment by FMaz008** [comment]
Done, will be in the next version.

**Comment by legion0** [comment]
fyi, you can link the fix here for tracking: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword
