### ISSUE TITLE
Extension malfunctioning since latest update

### ISSUE THREAD

**Issue by caffeinesplash** [FMaz008/VineHelper#29]
UK here, I haven't seen or heard anyone else mention issues with it, and it has been working great for me for the last couple of weeks (really appreciate) but I've tried on 3 different Windows machines now (Chrome and Firefox), and an Android phone, and the extension is quite broken for me at the moment, as far as I know it's since the latest version but I'm not certain.

![image](https://github.com/FMaz008/VineHelper/assets/158803794/be2e5db7-4ed3-43d2-b6fa-cd4140cc7f86)

Almost all items have the spinning wheel and won't load the top bar, the item count for each tab is missing ('Available ()' for example), and when clicking See details, it doesn't seem to load the ETV etc and I can't forward anything to Brenda on Discord via the button.

Last seen also doesn't seem to be working.

There are no errors in the console until I click on See details for an item, and then the following error appears:

![image](https://github.com/FMaz008/VineHelper/assets/158803794/e10bc534-b782-4e5d-83f5-1bb2b209105d)

It doesn't matter how long I wait, the items don't load, although occasionally certain items will partially load, like this one:

![image](https://github.com/FMaz008/VineHelper/assets/158803794/3ef33993-f41d-4c51-a0b9-f0d87f50f505)

Hiding/Showing items does still work. 

As I mentioned, the behaviour is the same for me across multiple devices, browsers, and networks, even if I install the extension fresh and use default settings.

**Comment by crysallis** [comment]
I'm submitted a pull request to fix this, once he's validated it you can test.

**Comment by FMaz008** [comment]
Validated and merged

**Comment by FMaz008** [comment]
Published as 2.0.9, I think this might be the bug I've been tracking for 3 days now that interrupted the listing to complete halfway trough or, when it had to deal with the first item with an ETV

**Comment by FMaz008** [comment]
Fixed by commit b43eddecd01ce0d754dd8b6c327ff6b5d4e7c9c0 v2.0.9 published.
