### ISSUE TITLE
Updated from repo 5 mins ago and everything is gone....

### ISSUE THREAD

**Issue by sorphin** [FMaz008/VineHelper#31]
It was all fine still before this pull..  I was able to revert back via git reset --keep HEAD@{1}

for reference, the pull was: Updating c8b5e44..f91395a

<img width="1980" alt="Screen Shot 2024-02-04 at 9 27 25 AM" src="https://github.com/FMaz008/VineHelper/assets/496131/606d332f-c2c1-41c7-a423-d896b0797fae">
<img width="1918" alt="Screen Shot 2024-02-04 at 9 26 32 AM" src="https://github.com/FMaz008/VineHelper/assets/496131/2be95a3a-4bea-4c90-96ce-da59141bd819">

**Comment by FMaz008** [comment]
Template cache needs to be reset. Checkout v 2.0.9, run a page, then pull the new code again.

**Comment by FMaz008** [comment]
You pulled between 2 of my commits...

**Comment by sorphin** [comment]
Repulled to 44a2dd6 (tagged 2.0.9), went and reloaded vine, repulled current. issue still. so I guess i'll just revert back again to 44a2dd6 unless you have any ideas then or want me to just go commit by commit?

**Comment by FMaz008** [comment]
It's just the template cache that neess reloaded. Usually that clears up
with version changes.

You can try the show version note popup trick.

**Comment by sorphin** [comment]
Just tried that. On 2.0.9, ticked the version popup box, reloaded the page, repulled to current. blank. hrmph.

**Comment by FMaz008** [comment]
No you need to pull to current, THEN clear the cache.

But I'll have to check the code, make it wait for the cache clearing to complete... that's a bug.

**Comment by sorphin** [comment]
and... apparently it's cache cleared.. stuff is finally back.. heh.  on the positive side.. it's really looking polished. good work.

**Comment by FMaz008** [comment]
You are sure that you pulled to the latest revision? I though I had fixed the issue in my very last comit, the one I submitted just after you created this bug report.

**Comment by sorphin** [comment]
The last pull I did when you just said to cache clear was: Updating 44a2dd6..2b526f2

Unless specified, I just do a normal 'git pull'

**Comment by sorphin** [comment]
I was on  c8b5e44e55caf7e1dc5f1fd564422b9717043dfb which I pulled yesterday at some point..
and when I had pulled today and had the issue, it shows i fast-forwarded to
f91395ab6fcf552640661b6eb2f79b3b04eba52b

**Comment by FMaz008** [comment]
Ok, I think we're ok.

There was a bug moving from 2.0.9 to 2.10.0 in f91395a . It would fail to coear the cache but set the new version to 2.10, so when moving to 2b526f2, cache wasn't cleared because the version had not changed.
