### ISSUE TITLE
First seen time all shows up as "NaN secs ago"

### ISSUE THREAD

**Issue by ss0s33** [FMaz008/VineHelper#33]
First seen time isn't working on my Firefox browser. I just see "NaN secs ago" for all items.
<img width="993" alt="screenshot" src="https://github.com/FMaz008/VineHelper/assets/105236218/a5bad6f1-15bc-42b0-aaa3-60fbe2598fb9">

**Comment by FMaz008** [comment]
I have a feeling this was linked to the timezone issues, which was fixed.

Have ypu encoutered this problem in the latest version?

**Comment by FMaz008** [comment]
@ss0s33 fixed?

**Comment by FMaz008** [comment]
Closing due to no reply, and lack of additional reports.
