### ISSUE TITLE
[FR] Make Hide All click the Next button

### ISSUE THREAD

**Issue by GeoNomad** [FMaz008/VineHelper#34]
When hiding all items on a page it would be convenient to also click the Next button.

I guess I am lazy...

Probably should be a selectable option.

Thanks for this great tool.

**Comment by FMaz008** [comment]
There is the key binding H for hide all and N for next page  ....

**Comment by GeoNomad** [comment]
Thanks for reminding me. I tend to be a mouse clicker.

I was thinking of adding to hideAllItems() in grid.js

document.dispatchEvent(new KeyboardEvent('keypress', {'key': 'n'})); 
or 
...whateveritis.click()

So after hiding, the page moves on automatically. But, as I said, lazy. I will stick to pressing H and N by finger.

Just came across your extension today. Looking forward to playing more with it.

😎

**Comment by FMaz008** [comment]
That would not be hard to do, as you figured, I'm just wondering if it would be a feature most people would enjoy, if it's worth making an option for it.

**Comment by crysallis** [comment]
For me, Not sure I'd use that... I'm not always going forward or next with hide all, many time it's on search pages that don't have a next.

**Comment by skotl** [comment]
Knowing the keyboard shortcuts are there (now!) is enough for me now. I think auto-forward, unless it had an option wrapping it, would confuse some users.
