### ISSUE TITLE
Move checkNewItems function to a Extension Service Worker

### ISSUE THREAD

**Issue by you-think-so-huh** [FMaz008/VineHelper#36]
First off: Good job on this project. It's an excellent tool.

I'm not an add-in developer, so I I might be mistaken about how things are designed to work.

I was watching the network activity from multiple tabs on my browser and saw that the add-in is calling back to the server for new items for every open tab (if it's not asleep). If I have 10 tabs open, it will send 10 requests for new items back to the server. This seems redundant.

This is not a problem for the user, but I expect that it will tax your server resources if everyone who has multiple tabs open are sending multiple requests to the server for the same information. I also expect this is a pretty common scenario.

I bring this up because I have seen the server busy message multiple times and was trying to think of ways to reduce the load on your server.

Another option might be to only send the new items request if the browser window is active.

Sorry if I'm off my rocker with this suggestion.

And for what it's worth, I'm running Chrome on Windows.

**Comment by FMaz008** [comment]
This is my first extension, so I won't pretend I know all the tricks, the title seems to imply you have an idea on hiw to make this work?

**Comment by you-think-so-huh** [comment]
> This is my first extension, so I won't pretend I know all the tricks, the title seems to imply you have an idea on how to make this work?

Fair enough. I haven't created one from scratch myself, I've just read [some things](https://developer.chrome.com/docs/extensions/develop/concepts/service-workers/basics). I'll create a branch and see what I can come up with. I usually dabble in node/typescript/react based JS applications so this will be a bit of a learning curve for me.

**Comment by FMaz008** [comment]
So a service worker is a script that will run as a singleton (1 entity) accross all the tabs?

Does it have the option to send a message to the tabs, so a listener could be implemented to make an action (ie: show a notification in the tab)?

**Comment by FMaz008** [comment]
Just letting you know this is in active development (on the serviceWorker branch) and should be released relatively soon.

**Comment by FMaz008** [comment]
Looks like it's working well. I'll close it as done. Will be release with the next version.
