### ISSUE TITLE
[FR] Add RFY AFA AI Key Bindings

### ISSUE THREAD

**Issue by LongDono** [FMaz008/VineHelper#39]
Building on the existing helpful key bindings (that I was going to implement until I saw it already was, thank you!), add 3 additional bindings:

[**R**]ecommended for you
Available for [**A**]ll
Additional [**I**]tems

When not on www.amazon.*/vine/vine-items, the extension could either ignore those keys or jump the user to that page and appropriate tab.

**Comment by FMaz008** [comment]
I like feature requests that are easy to implement. Good idea.

Except it won't be possible to highlight the A and I, but the key binding should be easy enough to add.

**Comment by FMaz008** [comment]
Done for the next release.
