### ISSUE TITLE
New Keybinding request

### ISSUE THREAD

**Issue by runew0lf** [FMaz008/VineHelper#45]
Could we have a keybinding of `1`, that takes you to page 1 of AI, i like forward and back but sometimes i just want to quckly go back to the first page again!

**Comment by FMaz008** [comment]
I  think "i" would do just that. ?

**Comment by skotl** [comment]
Interesting. On my laptop, it was still showing debug this morning but have just tried the same on the desktop and it works as you describe ("d" shows debug, "alt-d" does not).

**Comment by skotl** [comment]
Update: just checked the laptop and it is now working as specified. It's not impossible that I haven't used that laptop for three days so it might have still been on the older version this morning.
Thanks!

**Comment by FMaz008** [comment]
@skotl auto update can take a while to update sometimes. Probably just 2 different versions :)

**Comment by runew0lf** [comment]
Cheers buddy, i didnt even think of that one!
