### ISSUE TITLE
Difficult to read release notes with dark theme enabled

### ISSUE THREAD

**Issue by FiniteLooper** [FMaz008/VineHelper#46]
It appears to have dark text on a dark background for most of it.

![image](https://github.com/FMaz008/VineHelper/assets/463685/f480021b-840a-42f8-9c12-9bf2af0c3f77)

**Comment by crysallis** [comment]
A fix has been pushed to address this already.  Newest version is 2.2.2

**Comment by FiniteLooper** [comment]
Great! Yes I knew there was a newer version out when this popped up, but after updating to 2.2.2 I was not able to make the release notes show again to see if it was fixed.

**Comment by FMaz008** [comment]
The change log popup show only on major or minor release, not on revision or patches. (Ie: if the version is 1.2.3, it would show if 1 or 2 change, but not 3.)

To display it again, you can go in the options and check Clear Template cache.

On reload it will reload some static files and display the ChangeLog window again :)
