### ISSUE TITLE
New Error when typing in search bar asking me if I want to generate 10,000 dummy items in local storage (when I type a g in the search bar or on the page at all). I do NOT have keybindings turned on.

### ISSUE THREAD

**Issue by sorphin** [FMaz008/VineHelper#48]
<img width="458" alt="Screen Shot 2024-03-12 at 12 32 41 PM" src="https://github.com/FMaz008/VineHelper/assets/496131/0a7fc8bd-cd64-4fff-8231-763f3a41c749">

**Comment by FMaz008** [comment]
Found my secret way of testing for the Mega Hidders. Forgot to remove it. Fixed in 2.2.6
