### ISSUE TITLE
Infinite wheel spinning

### ISSUE THREAD

**Issue by iTsYaBoiiiiii** [FMaz008/VineHelper#55]
It seems some items still have the infinite spinning wheel despite Vine helper running:
![image](https://github.com/FMaz008/VineHelper/assets/32450703/6f4815ed-983f-48f1-b977-3a3e53dbd540)

The item in question: https://www.amazon.co.uk/dp/B0CRZFDGXL

**Comment by FMaz008** [comment]
There are multiple reason why this happens. Vine Helper fixes 2 of those problems so far.

This is very hard for me to investigate without 2 pieces of info that are not easy to get for most people.
I need to things:
1. A screenshot of the red error in the error console. (right click, Inspect to open the developer console, then the console tab. refresh the page and try again for the error to show)
2. Are you able to get me the Response, in Raw JSON format, received by the Ajax/XHR query of the content when trying to load this product ? Requests will be listed under the Network tab of the developer console. I suggest Reloading the page, clearing the Network tab using the "(/)" icon at the top left, and then clicking on See Details, and hit the stop button left of the (/) icon. You should only have a few queries to go through.

**Comment by iTsYaBoiiiiii** [comment]
Here's the error from the console: 
![image](https://github.com/FMaz008/VineHelper/assets/32450703/54bf152a-c103-4f36-90cf-5703dda9d25b)

The response for the request in JSON:
{
    "result": {
        "recommendationId": "A1F83G8C2ARO7P#B0CRZFDGXL#vine.enrollment.9e8753b6-cf23-4c84-b91e-647a2ad15dc5",
        "enrollmentAsinType": null,
        "item": null,
        "variations": [
            {
                "asin": "B0CRZFRG3S",
                "dimensions": {
                    "Style Name": "Style D:Bead"
                }
            }
        ]
    },
    "error": null
}

**Comment by FMaz008** [comment]
I'll add the : to the list of character to fix, I'm not sure but it seems to be what's causing the issue.

**Comment by FMaz008** [comment]
Are you able to install the latest code as a temporary extension in your browser of choice and test if the spinner error is fixed ? I just pushed the code to remove : from the variant name.

**Comment by FMaz008** [comment]
Ok, I'll close the issue but I feel that was likely the : causing the issue...

**Comment by iTsYaBoiiiiii** [comment]
The item showed up again today and the infinite wheel was still there on the official version.
I installed the latest commit and can confirm that it fixed the problem. Thanks!

**Comment by FMaz008** [comment]
Fantastic! Thanks for confirming!
