### ISSUE TITLE
Request: Option to toggle the "green styling"

### ISSUE THREAD

**Issue by runew0lf** [FMaz008/VineHelper#58]
It makes it very hard to read with darkmode on
![4nypPOIPjb](https://github.com/FMaz008/VineHelper/assets/9966016/664d8656-a6f8-4d6f-b218-19da935844df)
![msedge_XIHdZUqJDf](https://github.com/FMaz008/VineHelper/assets/9966016/4aaf17f2-4144-41a5-a67d-4ff5a0c5315a)
![msedge_5JHEZcWUKH](https://github.com/FMaz008/VineHelper/assets/9966016/5dbdcfba-ba83-4e50-a671-bf214bbf8d55)

As an "older gentleman" it kinda all blurs into one colour!

**Comment by FMaz008** [comment]
The main problem is the text color, which we will improve upon. But we have been working toward centralizing styling colors so it might be possible in the future (not yet) to have themes.

Baby steps...

... but for now we'll fix the text which is badly colored as you showed in your screenshots.

Thank you for giving feedback, some of those area haf not occured to me, so this is definitely helpful.

**Comment by crysallis** [comment]
I'll address this if you want

**Comment by FMaz008** [comment]
Fixed.
