### ISSUE TITLE
Notifications no longer working

### ISSUE THREAD

**Issue by anonymous721** [FMaz008/VineHelper#62]
- Browser: Firefox 115.8.0esr
- Vine Helper version: 2.4.1

As of yesterday's update (2.4.0), the notifications seem to have stopped working, both within Vine tabs and in the separate monitor tab. The Status line in the monitor reads "Not working, you need to refresh a vine page" but no combination of refreshing or reopening a vine page or window or the monitor tab seems to work.
When I check the console, I see the following error:
```
Uncaught (in promise) Error: Could not establish connection. Receiving end does not exist.
    onload moz-extension://068a6ae6-3d7b-405f-86ac-1a21cce96ffe/page/notifications.js:49
notifications.js:49:19
    apply self-hosted:2374
    applySafeWithoutClone resource://gre/modules/ExtensionCommon.sys.mjs:635
    wrapPromise resource://gre/modules/ExtensionCommon.sys.mjs:963
    (Async: promise callback)
    wrapPromise resource://gre/modules/ExtensionCommon.sys.mjs:922
    wrapPromise resource://gre/modules/ExtensionCommon.sys.mjs:921
    callAsyncFunction resource://gre/modules/ExtensionCommon.sys.mjs:1160
    callAsyncFunction resource://gre/modules/ExtensionChild.sys.mjs:737
    callAndLog resource://gre/modules/ExtensionChild.sys.mjs:708
    callAsyncFunction resource://gre/modules/ExtensionChild.sys.mjs:736
    stub resource://gre/modules/Schemas.sys.mjs:2897
    onload moz-extension://068a6ae6-3d7b-405f-86ac-1a21cce96ffe/page/notifications.js:49
```

**Comment by FMaz008** [comment]
Is the background script showing as running ?

**Comment by anonymous721** [comment]
I'm not entirely sure what to look for to answer that, sorry.

**Comment by FMaz008** [comment]
I think you should see it if you go to the debug options of Firefox:
[about:debugging#/runtime/this-firefox](about:debugging#/runtime/this-firefox)

**Comment by FMaz008** [comment]
Not that it will solve your problem, but to explain the monitor tab saying "Not working":
The tab does not know what country of Amazon you are using. It needs to know the country (domain) to make the request to the server to provide the recent items for your country.

When you refresh a tab from Vine, with the extension running, it will detect the domain being used and pass that information on to the service_worker/background script so it can start querying the server and pass the results to all the tabs which needs them. 

The Monitor tab will check if the country is known, if not it display (by default) that error to let you know that it doesn't know what country it is dealing with just yet.

With that being said, it sounds like your background script is failing to run properly for some reasons. The error you provided is the Monitor tab trying to talk with the background script but it can't find it.

Which leads me to believe it might have been de-activated for some reasons.

**Comment by anonymous721** [comment]
Right, that page is reporting the background script as stopped.

**Comment by FMaz008** [comment]
Any luck with disabling and enabling the extension?

Instructions here:
https://stackoverflow.com/questions/42062730/reload-installed-firefox-webextensions-background-script-for-debugging/42062968#42062968

**Comment by anonymous721** [comment]
The background script is still stopped, but now there's also three warning messages:
Reading manifest: Warning processing background.service_worker: An unexpected property was found in the WebExtension manifest.

Reading manifest: Warning processing permissions: Error processing permissions.1: Value "serviceWorker" must either: must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], be one of ["scripting"], or be one of ["webRequest", "webRequestBlocking", "webRequestFilterResponse", "webRequestFilterResponse.serviceWorkerScript"]], must either [be one of ["mozillaAddons"], be one of ["normandyAddonStudy"], be one of ["urlbar"], be one of ["activityLog"], be one of ["networkStatus"], or be one of ["telemetry"]], be one of ["alarms", "storage", "unlimitedStorage"], be one of ["captivePortal"], be one of ["identity"], be one of ["menus", "contextMenus"], be one of ["geckoProfiler"], be one of ["contextualIdentities"], be one of ["declarativeNetRequestWithHostAccess"], be one of ["dns"], or be one of ["theme"]], must either [must either [be one of ["idle"], be one of ["menus.overrideContext"], be one of ["search"], be one of ["activeTab"], be one of ["cookies"], be one of ["scripting"], or be one of ["webRequest", "webRequestBlocking", "webRequestFilterResponse", "webRequestFilterResponse.serviceWorkerScript"]], be one of ["clipboardRead", "clipboardWrite", "geolocation", "notifications"], be one of ["bookmarks"], be one of ["browsingData"], be one of ["devtools"], be one of ["find"], be one of ["history"], be one of ["pkcs11"], be one of ["sessions"], be one of ["tabs", "tabHide"], be one of ["topSites"], be one of ["browserSettings"], be one of ["declarativeNetRequestFeedback"], be one of ["downloads", "downloads.open"], be one of ["management"], be one of ["privacy"], be one of ["proxy"], be one of ["nativeMessaging"], or be one of ["webNavigation"]], be one of ["declarativeNetRequest"], or match the pattern /^experiments(\.\w+)+$/

Reading manifest: Warning processing options_ui.browser_style: "browser_style:true" has been deprecated in Manifest Version 3 and will be unsupported in the near future. While "options_ui.browser_style" was not explicitly specified in manifest.json, its default value was true. The default value of "options_ui.browser_style" has changed from true to false in Manifest Version 3.

**Comment by FMaz008** [comment]
The warning are fine, they are just properties needed for Chrome that Firefox does not support. It has no incidence on the background script running or not.

**Comment by FMaz008** [comment]
FYI the new releases of the extension, I made a separate manifest.json file for Firefox and Chrome, you should no longer have weird warnings. I don't think it will help your initial issue, but who knows...

**Comment by anonymous721** [comment]
The monitor is active and I'm getting notifications, so it seems to have done the trick.
