### ISSUE TITLE
Various things have disappeared.

### ISSUE THREAD

**Issue by sorphin** [FMaz008/VineHelper#7]
I discovered/installed this yesterday (01/27 - Chrome Extension version 1.15 iirc )and when I installed it, it showed an eye icon to hide/unhide items (and next to the hide/show all), as well as an ETV next to the ETV number, as of version 1.18 now, those are gone. Is this a bug or a change? because now I have to search where to click just to hide items. Nothing has changed with my browser since the original installation other than the extension self updating.

Browser: Chrome 120.0.6099.234
OS: MacOS 12.7.1

**Comment by FMaz008** [comment]
Confirmed as an issue introduced in v.0.17. Fixed for v0.19, which was just published a an emergency fix to the stored.
Thank you for reporting it!
