### ISSUE TITLE
Highlight tiles in the Notifications page based on keywords

### ISSUE THREAD

**Issue by testingillusions** [FMaz008/VineHelper#71]
To enhance the usefulness of the Notifications Monitoring page, there should be highlighting of tiles based on the defined Keyword list. 

This highlighting color should be different than the zero ETV so that those are still distinctive.

**Comment by testingillusions** [comment]
I've developed this functionality and would be happy to upload to a new branch for testing.

**Comment by FMaz008** [comment]
I'll probably just reuse the same code from and include it in the notification.js page when I have a moment. But by all mean, if you can do it faster; PR away my friend!

:)

**Comment by testingillusions** [comment]
Sounds good, happy to do that. Also, working on having different Notification sounds for that page... so far, it's working well. Can you give me developer permissions so that I can put the code in a new branch and submit the PR?

**Comment by FMaz008** [comment]
Make sure to do a separate PR for your sound idea, but yeah no need to ask permission :) I have to approve the PR anyway :)

**Comment by FMaz008** [comment]
Merged in, thank you ! :)
