### ISSUE TITLE
Notification Page Enhancements to improve sounds

### ISSUE THREAD

**Issue by testingillusions** [FMaz008/VineHelper#73]
There should be an option to provide Notifications with sound only when a ZeroETV or Keyword Match (Issue #71) is found to reduce the number of times the notification is triggered. 

To accomplish this, recommend the following be implemented:

- Add two new LastTriggered, one for ETV and Matched
- Add two new sounds to the resources, one for ETV and Matched
- Define logic to trigger these sounds and update LastTriggered in both ETV and Matched logic

**Comment by FMaz008** [comment]
It was hard enough to find a notification sound people did not complain of it being annoying, now you want us to find **2 MORE** ?! Kidding, but seriously we'll need to find 2 sounds that are royalty free and all first.

Not a bad idea, just got other priorities on the go for the short term :)

**Comment by FMaz008** [comment]
Done with v2.8, you can now select specific sounds for zero ETV or keyword match or regular notification or on screen notifications. And volume control too.

If you have more sounds to suggest which are royalty free, feel free to send them my way and I can add them.
