### ISSUE TITLE
First launch Popup offering privacy-based setting profile (for EU compliance)

### ISSUE THREAD

**Issue by FMaz008** [FMaz008/VineHelper#8]
In Europe, websites need to disclose the privacy implication of the use of their sites. Users are used to be asked what kind of cookies they wants to allow.

It was requested for Vine Helper do so something similar in showing a popup which would recommend 2 settings profiles, with privacy-base explanations for each.

This feature would be a popup in first launch with 2 columns. Rough idea:
**Column1:** Share everything (Allow vine Helper to collect all the data it requires to have all its features operating) (BUTTON use the recommended settings)
**Column2:** Do not share (Disable all sharing options. Note that Vine Helper still collect ASIN# of the item in your listing if you use any features that request information from the server.) (BUTTON use the limited sharing)

You can change the settings at anytime in the extension options.

**Comment by skotl** [comment]
Is this definitely required under EU regs? The helper isn't a website and has been consciously installed by the user a couple of seconds before this popup would appear.
I'm not religiously opposed to the enhancement request (and it is reasonably good practise) just doubting that the regulations cover browser extensions.
