### ISSUE TITLE
High CPU usage after a while; ongoing

### ISSUE THREAD

**Issue by DerekTP** [FMaz008/VineHelper#88]
Hi... I notice that sometimes my laptop gets reeaaallllyyy sluggish, and task manager shows CPU regularly peaking in a sawtooth pattern. TM identifies Chrome as using the bulk of CPU, and Chrome's own task manager narrows it down to Vine Helper. Here's the "CPU performance" chart from task manager - I shut off VH about half way through, and the system had been "idle" throughout the period traced.
![vh](https://github.com/FMaz008/VineHelper/assets/123762669/82e429e5-445c-44c3-a85b-4167668657f2)
I usually keep a Vine tab open all the time; today I'd not used it for a couple of hours and the performance problem was noticeable whenever I was using other Chrome tabs, or switching to/from Chrome.  (This on Windows 10 BTW). 
Happy to track whatever else you need me to look at ... (am a web developer myself).  I know you had some CPU-related issues a couple of weeks back; don't know if this is related.
Thanks so much for the work you do on VH - makes Vine a LOT easier! :-)

**Comment by FMaz008** [comment]
We are aware of that issue for people having lots of tabs open.

We are both working on a refactor of the entire notification system as well as trying to hunt and fix the current issue.

Do you have the notification monitor open or closed?

**Comment by FMaz008** [comment]
I believe this to be fixed by the latest commit where I implemented a new broadcast system. Can you test the latest code on GIT to confirm?

**Comment by ShaneDelmore** [comment]
I can confirm it resolved the issue for me, running with an embarrassing number of tabs open.
