### ISSUE TITLE
Available / Unavailable / Hidden tabs should be sticky.

### ISSUE THREAD

**Issue by LeonLoo** [FMaz008/VineHelper#91]
Available / Unavailable / Hidden tabs should be sticky.  So when I click on "Hidden" then I navigate to the "Next" page or navigate to a specific page number it continues to show me "Hidden" items.

Use case:  I have a fairly extensive list of auto-hide keywords and sometimes something interesting gets hidden so I like scanning through all the hidden items but each time I navigate to a new page I have to re-select the "Hidden" tab.  A bit of a pain when there are over 100 pages.

Thanks for taking the time to read and consider my request.

**Comment by skotl** [comment]
I wonder whether this could also be addressed by adding keyboard shortcuts for Available, Unavailable & Hidden?
Then at least you could (if you bound "x" to "Unavailable"), hit nx, nx, nx...

Of course this is me assuming that adding another key binding is easier than making the selected tab sticky! If it's not then I agree your suggestion is reasonable.

**Comment by FMaz008** [comment]
Done with configurable keyboard shortcuts, 8af440e12b2c22656db89c9d4944ec94bb3a8de5, will be part of v2.9
