### ISSUE TITLE
Unavailable should be prioritized over Hidden

### ISSUE THREAD

**Issue by LeonLoo** [FMaz008/VineHelper#92]
If an item is "Unavailable" and "Hidden" then currently it'll appear in the "Hidden" tab.  I'd suggest it makes more sense to put them into the "Unavailable" tab.  

Use case:  I like scanning through the "Hidden" items but "Unavailable" items keep catching my eye.  Since I can't order "Unavailable" items I'd rather not see them in the "Hidden" tab.

Thanks for reviewing and considering my suggestion.

**Comment by FMaz008** [comment]
Reading your 2 suggestions I feel you are not using hidden as intended.

Hidden are things you are absolutely sure you don't want. Not things you review as part of a routine.

A lot of people test unavailable items to see if the item was changed (which happens sometimes - rarely), but if it's hidden they don't want to see it.

**Comment by LeonLoo** [comment]
I see.  Yes, perhaps I'm not using hidden as intended, but I wonder if there are many others who use it like I do.

The Keywords feature to auto-hide items is very handy (who want's to page through dozens and dozens of keychains), but sometimes something good is auto-hidden (Bluetooth earbuds with handy keychain).  No worries if there's little support for my use case, it's still a very helpful tool and I'll continue to use it every day.

**Comment by FMaz008** [comment]
Closed as the highlight list already superseed the hidden keywords and most people would not be favourable to reversing the priority order.
