### ISSUE TITLE
Looks like someone has managed to post some false items.

### ISSUE THREAD

**Issue by LeonLoo** [FMaz008/VineHelper#95]
I don't know how best to alert the developers so I'm posting here, delete if I did it wrong.

I just got notified for a bunch of items named "YUM YUM YUM" along with an inappropriate images.

![2024-04-11-14-11-58-007](https://github.com/FMaz008/VineHelper/assets/8838185/48fa4bf4-305f-459d-b423-dba65b0df4d0)

**Comment by LeonLoo** [comment]
The image is being served from a Russian site:
![Screenshot 2024-04-11 142240](https://github.com/FMaz008/VineHelper/assets/8838185/c1f71a01-e13a-4764-9d5e-acfec968ffe4)

**Comment by FMaz008** [comment]
Yeah, some kid was uploading false listing in the API. I addressed it.
